/**
 * Programmatic SEO — Glossary of business/startup terms in Arabic.
 * Pages: /glossary and /glossary/[term]
 */

export interface GlossaryTerm {
  slug: string;
  termAr: string;
  termEn: string;
  shortDefinitionAr: string;
  fullDefinitionAr: string;
  category:
    | 'finance'
    | 'product'
    | 'marketing'
    | 'sales'
    | 'legal'
    | 'tech'
    | 'hr'
    | 'fundraising';
  examples?: string[];
  relatedTerms?: string[];
  keywords: string[];
}

export const GLOSSARY: GlossaryTerm[] = [
  {
    slug: 'mvp',
    termAr: 'MVP (الحد الأدنى للمنتج)',
    termEn: 'Minimum Viable Product',
    shortDefinitionAr: 'أول نسخة من منتجك تختبر فرضية أساسية بأقل جهد ممكن.',
    fullDefinitionAr: 'الـ MVP هو نسخة منتج لها فقط الـ features الأساسية الكافية لجمع feedback من المستخدمين الأوائل. الفكرة من Eric Ries في Lean Startup. الهدف ليس "منتج رديء"، بل "أصغر تجربة قابلة للتعلم منها".',
    category: 'product',
    examples: ['Airbnb بدأت بصفحة بسيطة لشقة واحدة', 'Dropbox بدأت بفيديو يشرح المنتج فقط'],
    relatedTerms: ['pmf', 'lean-startup', 'iteration'],
    keywords: ['MVP', 'minimum viable product', 'منتج', 'lean startup'],
  },
  {
    slug: 'pmf',
    termAr: 'Product-Market Fit',
    termEn: 'Product-Market Fit',
    shortDefinitionAr: 'الحالة التي يكون فيها منتجك يحل مشكلة حقيقية لسوق محدد بشكل يجعل النمو organic.',
    fullDefinitionAr: 'PMF هو نقطة التحول في حياة الستارت أب. قبلها، أنت تدفع لكل مستخدم. بعدها، المستخدمون يأتون من تلقاء أنفسهم. علاماتها: Sean Ellis Test > 40%، NPS > 40، organic growth > 20%.',
    category: 'product',
    relatedTerms: ['mvp', 'nps', 'churn'],
    keywords: ['PMF', 'product market fit', 'منتج سوق'],
  },
  {
    slug: 'cac',
    termAr: 'CAC (تكلفة استحواذ العميل)',
    termEn: 'Customer Acquisition Cost',
    shortDefinitionAr: 'إجمالي التكلفة لجلب عميل جديد، تشمل marketing وsales وtools.',
    fullDefinitionAr: 'CAC = (إجمالي مصاريف Sales + Marketing) ÷ (عدد العملاء الجدد). يجب فحصه بـ blended وorganic وpaid منفصلين. CAC وحده غير كافي - يجب مقارنته بـ LTV.',
    category: 'finance',
    examples: ['CAC = $30 يعني تدفع $30 لجلب كل عميل جديد'],
    relatedTerms: ['ltv', 'payback', 'cac-payback'],
    keywords: ['CAC', 'customer acquisition cost', 'تكلفة العميل'],
  },
  {
    slug: 'ltv',
    termAr: 'LTV (القيمة العمرية للعميل)',
    termEn: 'Lifetime Value',
    shortDefinitionAr: 'إجمالي الإيراد المتوقع من عميل واحد طوال علاقته بمنتجك.',
    fullDefinitionAr: 'LTV = ARPU × Gross Margin × (1/Churn Rate). الـ LTV الصحي يكون 3× CAC على الأقل. للستارت أبس الـ early stage، حسابه صعب لقصر التاريخ، لذا استخدم cohort analysis.',
    category: 'finance',
    relatedTerms: ['cac', 'churn', 'arpu'],
    keywords: ['LTV', 'lifetime value', 'قيمة العميل'],
  },
  {
    slug: 'churn',
    termAr: 'Churn (معدل الفقدان)',
    termEn: 'Churn Rate',
    shortDefinitionAr: 'نسبة العملاء الذين يلغون اشتراكهم في فترة معينة.',
    fullDefinitionAr: 'Customer Churn = العملاء المفقودون ÷ إجمالي العملاء في بداية الفترة. Revenue Churn = الإيراد المفقود ÷ إجمالي الإيراد. Net Negative Churn هو الـ holy grail (expansion > churn).',
    category: 'finance',
    relatedTerms: ['ltv', 'retention', 'nrr'],
    keywords: ['churn', 'فقدان العملاء', 'retention'],
  },
  {
    slug: 'mrr',
    termAr: 'MRR (الإيراد الشهري المتكرر)',
    termEn: 'Monthly Recurring Revenue',
    shortDefinitionAr: 'إجمالي الإيراد المتكرر المتوقع شهرياً من اشتراكاتك النشطة.',
    fullDefinitionAr: 'MRR = Σ (عدد العملاء × سعر الاشتراك الشهري). يجب فصل New MRR، Expansion MRR، Contraction MRR، وChurned MRR لفهم الـ growth motion.',
    category: 'finance',
    relatedTerms: ['arr', 'churn', 'nrr'],
    keywords: ['MRR', 'monthly recurring revenue', 'إيراد شهري'],
  },
  {
    slug: 'arr',
    termAr: 'ARR (الإيراد السنوي المتكرر)',
    termEn: 'Annual Recurring Revenue',
    shortDefinitionAr: 'MRR × 12. الـ metric الأساسي للـ SaaS النامية.',
    fullDefinitionAr: 'ARR = MRR × 12. الـ VCs يقيسون الـ SaaS بـ ARR. Milestones مهمة: $1M ARR (Series A)، $10M ARR (Series B).',
    category: 'finance',
    relatedTerms: ['mrr', 'series-a', 'series-b'],
    keywords: ['ARR', 'annual recurring revenue', 'إيراد سنوي'],
  },
  {
    slug: 'nrr',
    termAr: 'NRR (Net Revenue Retention)',
    termEn: 'Net Revenue Retention',
    shortDefinitionAr: 'كم يدفع cohort واحد بعد سنة كاملة، شامل expansion وchurn.',
    fullDefinitionAr: 'NRR = (Starting MRR + Expansion - Contraction - Churn) ÷ Starting MRR. > 100% = الشركة تنمو حتى بدون عملاء جدد. أفضل SaaS تحقق 130%+.',
    category: 'finance',
    relatedTerms: ['mrr', 'churn', 'expansion'],
    keywords: ['NRR', 'net revenue retention'],
  },
  {
    slug: 'arpu',
    termAr: 'ARPU (متوسط الإيراد لكل مستخدم)',
    termEn: 'Average Revenue Per User',
    shortDefinitionAr: 'إجمالي الإيراد ÷ عدد المستخدمين النشطين.',
    fullDefinitionAr: 'ARPU = Total Revenue ÷ Active Users. مهم لمعرفة قيمة العميل. ARPU ≠ ARPPU (paying user).',
    category: 'finance',
    relatedTerms: ['ltv', 'mrr'],
    keywords: ['ARPU', 'متوسط إيراد'],
  },
  {
    slug: 'tam-sam-som',
    termAr: 'TAM / SAM / SOM',
    termEn: 'Total/Serviceable/Obtainable Market',
    shortDefinitionAr: 'TAM = السوق الكلي. SAM = ما يمكنك خدمته. SOM = ما يمكنك الحصول عليه.',
    fullDefinitionAr: 'TAM (Total Addressable Market): إجمالي طلب السوق على الفئة. SAM (Serviceable Addressable Market): جزء يمكن لمنتجك خدمته. SOM (Serviceable Obtainable Market): الـ market share الواقعي. كلها أرقام يجب defendable.',
    category: 'fundraising',
    relatedTerms: ['market-sizing', 'pitch-deck'],
    keywords: ['TAM', 'SAM', 'SOM', 'حجم السوق'],
  },
  {
    slug: 'series-a',
    termAr: 'Series A (السلسلة أ)',
    termEn: 'Series A',
    shortDefinitionAr: 'جولة تمويل بعد PMF لـ scaling. عادة $5-15M في MENA.',
    fullDefinitionAr: 'Series A تأتي بعد إثبات PMF و$1M+ ARR. تستخدم للـ scaling: hiring، marketing، expansion. dilution عادة 20-30%.',
    category: 'fundraising',
    relatedTerms: ['seed', 'series-b', 'pmf'],
    keywords: ['series a', 'سيريز إيه', 'venture capital'],
  },
  {
    slug: 'seed',
    termAr: 'Seed (التمويل الأولي)',
    termEn: 'Seed Funding',
    shortDefinitionAr: 'أول جولة تمويل institutional. عادة $500K-$3M.',
    fullDefinitionAr: 'Seed تأتي بعد pre-seed/angel وقبل Series A. للـ MVP وأول traction. عادة من VCs متخصصين في seed.',
    category: 'fundraising',
    relatedTerms: ['pre-seed', 'series-a'],
    keywords: ['seed', 'تمويل seed', 'funding'],
  },
  {
    slug: 'safe',
    termAr: 'SAFE (اتفاقية الـ Future Equity)',
    termEn: 'Simple Agreement for Future Equity',
    shortDefinitionAr: 'وثيقة استثمار بسيطة من Y Combinator، تتحول لـ equity في الـ priced round التالية.',
    fullDefinitionAr: 'SAFE تجنبك تعقيدات valuation في الـ early stage. لها valuation cap وdiscount. تحولها لـ equity في الـ next priced round (عادة Series A).',
    category: 'fundraising',
    relatedTerms: ['convertible-note', 'pre-money'],
    keywords: ['SAFE', 'Y combinator', 'investment'],
  },
  {
    slug: 'cap-table',
    termAr: 'Cap Table (جدول الملكية)',
    termEn: 'Capitalization Table',
    shortDefinitionAr: 'جدول يوضح ملكية كل مساهم في الشركة.',
    fullDefinitionAr: 'Cap table يحتوي: Founders، ESOP، investors. يجب تحديثه بعد كل round وكل grant. أدوات: Carta، Pulley، Excel.',
    category: 'fundraising',
    relatedTerms: ['esop', 'dilution'],
    keywords: ['cap table', 'جدول الملكية', 'equity'],
  },
  {
    slug: 'esop',
    termAr: 'ESOP (خطة خيارات الموظفين)',
    termEn: 'Employee Stock Option Plan',
    shortDefinitionAr: 'حصص محجوزة للموظفين، عادة 10-15% من الشركة.',
    fullDefinitionAr: 'ESOP pool يُحجز قبل الـ Series A عادة. يُمنح للموظفين بـ vesting (4 سنوات + 1 cliff). يقلل الـ dilution على الـ founders.',
    category: 'fundraising',
    relatedTerms: ['vesting', 'cliff', 'cap-table'],
    keywords: ['ESOP', 'employee stock', 'equity'],
  },
  {
    slug: 'vesting',
    termAr: 'Vesting (الاستحقاق التدريجي)',
    termEn: 'Vesting',
    shortDefinitionAr: 'الحصول على الـ equity تدريجياً بدلاً من مرة واحدة.',
    fullDefinitionAr: 'Standard vesting: 4 سنوات مع 1 سنة cliff. أول سنة، تحصل على 25%. بعدها، 1/48 شهرياً. يحمي الشركة من founders/employees يخرجون مبكراً.',
    category: 'fundraising',
    relatedTerms: ['cliff', 'esop'],
    keywords: ['vesting', 'استحقاق', 'equity'],
  },
  {
    slug: 'burn-rate',
    termAr: 'Burn Rate (معدل الحرق)',
    termEn: 'Burn Rate',
    shortDefinitionAr: 'كم تنفق شهرياً (gross) أو كم تخسر (net) شهرياً.',
    fullDefinitionAr: 'Gross Burn = إجمالي المصاريف. Net Burn = المصاريف - الإيراد. يقاس شهرياً. Runway = Cash on Hand ÷ Net Burn.',
    category: 'finance',
    relatedTerms: ['runway', 'cash-flow'],
    keywords: ['burn rate', 'معدل حرق', 'startup finance'],
  },
  {
    slug: 'runway',
    termAr: 'Runway (مدة البقاء)',
    termEn: 'Runway',
    shortDefinitionAr: 'كم شهر يكفيك الكاش الحالي قبل النفاد.',
    fullDefinitionAr: 'Runway = Cash on Hand ÷ Monthly Net Burn. < 6 شهور = خطر. 12-18 شهر = آمن. 24+ = ممتاز. ابدأ fundraising عند 9-12 شهر.',
    category: 'finance',
    relatedTerms: ['burn-rate', 'fundraising'],
    keywords: ['runway', 'مدة البقاء', 'cash'],
  },
  {
    slug: 'unit-economics',
    termAr: 'Unit Economics',
    termEn: 'Unit Economics',
    shortDefinitionAr: 'الأرباح والخسائر على مستوى الوحدة (عميل واحد، طلب واحد).',
    fullDefinitionAr: 'Unit Economics = هل عميل واحد ربحي بعد كل تكاليفه؟ المكونات: ARPU، COGS، CAC، Payback. سيئة = الموت محقق مع التوسع.',
    category: 'finance',
    relatedTerms: ['cac', 'ltv', 'gross-margin'],
    keywords: ['unit economics', 'اقتصاديات الوحدة'],
  },
  {
    slug: 'gross-margin',
    termAr: 'Gross Margin (الهامش الإجمالي)',
    termEn: 'Gross Margin',
    shortDefinitionAr: '(الإيراد - COGS) ÷ الإيراد. مهم جداً للـ SaaS (>70%).',
    fullDefinitionAr: 'Gross Margin يقيس كفاءة المنتج الأساسي. SaaS صحي = 70-85%. Hardware = 30-50%. Services = 30-60%. ضعيف = صعب التوسع.',
    category: 'finance',
    relatedTerms: ['cogs', 'unit-economics'],
    keywords: ['gross margin', 'هامش ربح'],
  },
  {
    slug: 'b2b-vs-b2c',
    termAr: 'B2B vs B2C',
    termEn: 'B2B vs B2C',
    shortDefinitionAr: 'B2B = البيع للشركات. B2C = البيع للأفراد.',
    fullDefinitionAr: 'B2B: عقود أكبر، sales cycle أطول، ACV أعلى، churn أقل. B2C: viral قابل، transactional، churn أعلى. مختلف في كل شيء (sales، marketing، product).',
    category: 'sales',
    relatedTerms: ['enterprise', 'self-serve'],
    keywords: ['B2B', 'B2C', 'business model'],
  },
  {
    slug: 'icp',
    termAr: 'ICP (الملف المثالي للعميل)',
    termEn: 'Ideal Customer Profile',
    shortDefinitionAr: 'وصف دقيق لنوع العميل الأنسب لمنتجك.',
    fullDefinitionAr: 'ICP يحدد: Industry، Size، Geography، Budget، Use case، Pain points. كلما كان أدق، كلما كان sales أسهل وchurn أقل.',
    category: 'sales',
    relatedTerms: ['persona', 'segmentation'],
    keywords: ['ICP', 'ideal customer', 'targeting'],
  },
  {
    slug: 'persona',
    termAr: 'Persona (الشخصية المستهدفة)',
    termEn: 'Buyer Persona',
    shortDefinitionAr: 'وصف تخيلي لشخص نموذجي يمثل segment معين.',
    fullDefinitionAr: 'Persona تحتوي: name، age، job، goals، challenges، sources. تساعد على empathy وdecisions. اعمل 2-3 personas، لا 10.',
    category: 'marketing',
    relatedTerms: ['icp', 'segmentation'],
    keywords: ['persona', 'شخصية مستهدفة', 'buyer persona'],
  },
  {
    slug: 'positioning',
    termAr: 'Positioning (التموضع)',
    termEn: 'Positioning',
    shortDefinitionAr: 'كيف يدرك العميل منتجك مقارنة بالمنافسين.',
    fullDefinitionAr: 'Positioning = (للـ ICP) (الـ category) (هو الأفضل في) (differentiator). مثال April Dunford. أهم decision في الـ marketing.',
    category: 'marketing',
    relatedTerms: ['icp', 'category', 'differentiation'],
    keywords: ['positioning', 'تموضع', 'brand'],
  },
  {
    slug: 'go-to-market',
    termAr: 'GTM (استراتيجية الدخول للسوق)',
    termEn: 'Go-to-Market Strategy',
    shortDefinitionAr: 'الخطة الكاملة لكيفية وصول منتجك للعملاء.',
    fullDefinitionAr: 'GTM يتضمن: Positioning، Pricing، Channels، Sales motion، Content، Launch plan. يختلف لكل segment وstage.',
    category: 'marketing',
    relatedTerms: ['positioning', 'sales', 'plg'],
    keywords: ['GTM', 'go to market', 'launch'],
  },
  {
    slug: 'plg',
    termAr: 'PLG (Product-Led Growth)',
    termEn: 'Product-Led Growth',
    shortDefinitionAr: 'نموذج نمو حيث المنتج نفسه يجذب ويحول ويحتفظ بالعملاء.',
    fullDefinitionAr: 'PLG يعتمد على freemium/free trial، self-serve onboarding، viral mechanics، usage-based pricing. أمثلة: Slack، Notion، Figma. يقلل CAC بشكل كبير.',
    category: 'marketing',
    relatedTerms: ['freemium', 'self-serve', 'viral-coefficient'],
    keywords: ['PLG', 'product led growth', 'self serve'],
  },
  {
    slug: 'nps',
    termAr: 'NPS (مؤشر صافي المروجين)',
    termEn: 'Net Promoter Score',
    shortDefinitionAr: 'سؤال واحد: كم احتمالية أن توصي بمنتجنا؟ (0-10).',
    fullDefinitionAr: 'NPS = % Promoters (9-10) - % Detractors (0-6). > 50 ممتاز. > 70 استثنائي. أداة بسيطة لقياس satisfaction.',
    category: 'marketing',
    relatedTerms: ['csat', 'customer-success'],
    keywords: ['NPS', 'net promoter', 'satisfaction'],
  },
  {
    slug: 'aha-moment',
    termAr: 'Aha Moment (لحظة الإدراك)',
    termEn: 'Aha Moment',
    shortDefinitionAr: 'اللحظة التي يدرك فيها المستخدم قيمة منتجك.',
    fullDefinitionAr: 'Aha moment هي action يقوم به المستخدم تجعله يفهم القيمة. Facebook: 7 friends in 10 days. Twitter: follow 30 accounts. Time to Aha أهم metric في activation.',
    category: 'product',
    relatedTerms: ['activation', 'onboarding'],
    keywords: ['aha moment', 'لحظة الإدراك', 'activation'],
  },
  {
    slug: 'kyc',
    termAr: 'KYC (اعرف عميلك)',
    termEn: 'Know Your Customer',
    shortDefinitionAr: 'إجراءات التحقق من هوية العميل، مطلوبة قانونياً في الفنتك.',
    fullDefinitionAr: 'KYC تشمل: ID verification، address proof، biometric. مطلوبة من البنك المركزي للفنتك. تكلفة: $1-5 لكل verification.',
    category: 'legal',
    relatedTerms: ['aml', 'compliance'],
    keywords: ['KYC', 'اعرف عميلك', 'compliance'],
  },
  {
    slug: 'aml',
    termAr: 'AML (مكافحة غسل الأموال)',
    termEn: 'Anti-Money Laundering',
    shortDefinitionAr: 'إجراءات وتقارير لمنع غسل الأموال عبر منتجك.',
    fullDefinitionAr: 'AML تتضمن: transaction monitoring، suspicious activity reports (SAR)، sanctions screening. مطلوبة قانونياً في كل فنتك.',
    category: 'legal',
    relatedTerms: ['kyc', 'compliance'],
    keywords: ['AML', 'مكافحة غسل أموال'],
  },
  {
    slug: 'pdpl',
    termAr: 'PDPL (قانون حماية البيانات)',
    termEn: 'Personal Data Protection Law',
    shortDefinitionAr: 'قانون مصري 151/2020 وسعودي مشابه يحمي البيانات الشخصية.',
    fullDefinitionAr: 'PDPL المصري يشبه GDPR في 80%. يفرض: consent واضح، حق المسح، DPO، تقارير للجهة. غرامات تصل لـ 10M جنيه.',
    category: 'legal',
    relatedTerms: ['gdpr', 'privacy'],
    keywords: ['PDPL', 'حماية بيانات', 'قانون 151'],
  },
  {
    slug: 'gdpr',
    termAr: 'GDPR (اللائحة الأوروبية)',
    termEn: 'General Data Protection Regulation',
    shortDefinitionAr: 'قانون حماية بيانات أوروبي. ينطبق على أي شركة تخدم EU.',
    fullDefinitionAr: 'GDPR صارم. غرامات تصل 4% من الإيراد العالمي. مطلوب: lawful basis، consent، DPO، 72h breach notification، DPIAs.',
    category: 'legal',
    relatedTerms: ['pdpl', 'privacy'],
    keywords: ['GDPR', 'حماية بيانات', 'EU'],
  },
  {
    slug: 'soc-2',
    termAr: 'SOC 2',
    termEn: 'SOC 2',
    shortDefinitionAr: 'شهادة أمنية لـ SaaS تطلبها المؤسسات الأمريكية.',
    fullDefinitionAr: 'SOC 2 من AICPA. Type 1 = نقطة زمنية. Type 2 = فترة 12 شهر. مطلوبة لبيع الـ enterprise. تكلفة: $20-100K.',
    category: 'legal',
    relatedTerms: ['iso-27001', 'compliance'],
    keywords: ['SOC 2', 'security audit'],
  },
  {
    slug: 'rag',
    termAr: 'RAG (Retrieval-Augmented Generation)',
    termEn: 'RAG',
    shortDefinitionAr: 'تقنية AI تجمع بين بحث في قاعدة بيانات وتوليد LLM.',
    fullDefinitionAr: 'RAG يحل مشكلة الـ LLM hallucinations. يبحث في documents، يُحضر relevant chunks، يمررها للـ LLM للإجابة. أساسي لأي AI product.',
    category: 'tech',
    relatedTerms: ['llm', 'embeddings', 'vector-db'],
    keywords: ['RAG', 'retrieval', 'LLM'],
  },
  {
    slug: 'llm',
    termAr: 'LLM (نماذج اللغة الكبيرة)',
    termEn: 'Large Language Model',
    shortDefinitionAr: 'نماذج AI كبيرة مثل GPT-4 و Claude و Gemini.',
    fullDefinitionAr: 'LLMs مدربة على billions من النصوص. قادرة على text، code، reasoning. أمثلة: GPT-4 (OpenAI)، Claude (Anthropic)، Gemini (Google).',
    category: 'tech',
    relatedTerms: ['rag', 'fine-tuning', 'prompt-engineering'],
    keywords: ['LLM', 'AI', 'GPT'],
  },
  {
    slug: 'fine-tuning',
    termAr: 'Fine-tuning (الضبط الدقيق)',
    termEn: 'Fine-tuning',
    shortDefinitionAr: 'تدريب نموذج موجود على بياناتك الخاصة لتحسين أداءه.',
    fullDefinitionAr: 'Fine-tuning يعدل weights الـ LLM ليؤدي أفضل في domain محدد. أرخص من training from scratch لكن لا يزال مكلف ($1-50K).',
    category: 'tech',
    relatedTerms: ['llm', 'rag'],
    keywords: ['fine-tuning', 'تدريب', 'AI'],
  },
  {
    slug: 'embeddings',
    termAr: 'Embeddings (التضمينات)',
    termEn: 'Embeddings',
    shortDefinitionAr: 'تمثيل النصوص كأرقام لاستخدامها في AI ومحركات البحث.',
    fullDefinitionAr: 'Embeddings تحول text → vector (مثلاً 1536 رقم). نصوص متشابهة لها vectors قريبة. أساس RAG وsemantic search.',
    category: 'tech',
    relatedTerms: ['rag', 'vector-db'],
    keywords: ['embeddings', 'vectors', 'AI'],
  },
  {
    slug: 'vector-db',
    termAr: 'Vector Database',
    termEn: 'Vector Database',
    shortDefinitionAr: 'قاعدة بيانات متخصصة في تخزين والبحث في embeddings.',
    fullDefinitionAr: 'Vector DBs (Pinecone، Weaviate، pgvector) تستخدم HNSW أو IVF للبحث السريع في millions من vectors. أساس RAG.',
    category: 'tech',
    relatedTerms: ['embeddings', 'rag'],
    keywords: ['vector database', 'pinecone', 'pgvector'],
  },
  {
    slug: 'mcp',
    termAr: 'MCP (Model Context Protocol)',
    termEn: 'Model Context Protocol',
    shortDefinitionAr: 'بروتوكول من Anthropic لربط LLMs بـ tools وdata sources.',
    fullDefinitionAr: 'MCP يجعل LLMs قادرة على استدعاء tools خارجية بشكل موحد. مدعوم في Claude، Cursor، vscode. مستقبل الـ AI agents.',
    category: 'tech',
    relatedTerms: ['llm', 'agents'],
    keywords: ['MCP', 'model context protocol', 'agents'],
  },
  {
    slug: 'multi-agent',
    termAr: 'Multi-Agent (أنظمة الوكلاء المتعددين)',
    termEn: 'Multi-Agent System',
    shortDefinitionAr: 'نظام يستخدم عدة AI agents متخصصين يعملون معاً.',
    fullDefinitionAr: 'بدلاً من LLM واحد يفعل كل شيء، multi-agent: agent للـ research، agent للـ writing، agent للـ review. أكثر دقة وقابلية للتوسع.',
    category: 'tech',
    relatedTerms: ['llm', 'agents', 'orchestration'],
    keywords: ['multi-agent', 'AI agents', 'وكلاء'],
  },
  {
    slug: 'fawry',
    termAr: 'فوري (Fawry)',
    termEn: 'Fawry',
    shortDefinitionAr: 'منصة دفع إلكترونية مصرية رائدة، خاصة للـ COD.',
    fullDefinitionAr: 'Fawry تخدم 50M+ مصري. تكامل أساسي لأي تطبيق دفع في مصر. تقدم: bill payment، wallet، lending، POS.',
    category: 'finance',
    relatedTerms: ['payment', 'instapay'],
    keywords: ['Fawry', 'فوري', 'دفع'],
  },
  {
    slug: 'instapay',
    termAr: 'InstaPay',
    termEn: 'InstaPay',
    shortDefinitionAr: 'نظام تحويل فوري بين البنوك المصرية، أطلقه البنك المركزي.',
    fullDefinitionAr: 'InstaPay يتيح تحويل مجاني وفوري بين البنوك. تكامل أساسي لأي فنتك. APIs متاحة عبر البنوك.',
    category: 'finance',
    relatedTerms: ['fawry', 'payment'],
    keywords: ['InstaPay', 'انستا باي', 'تحويل'],
  },
  {
    slug: 'cod',
    termAr: 'COD (الدفع عند الاستلام)',
    termEn: 'Cash on Delivery',
    shortDefinitionAr: 'الدفع نقداً عند تسليم الطلب. سائد في مصر (60-70%).',
    fullDefinitionAr: 'COD يحل ثقة العميل لكنه مكلف: returns 25-40%، collection costs، cash handling. ابدأ به ثم انقل للدفع المسبق تدريجياً.',
    category: 'finance',
    relatedTerms: ['fawry', 'payment'],
    keywords: ['COD', 'الدفع عند الاستلام'],
  },
  {
    slug: 'free-zone',
    termAr: 'Free Zone (المنطقة الحرة)',
    termEn: 'Free Zone',
    shortDefinitionAr: 'مناطق إماراتية تُعفي الشركات من ضرائب وتسمح بـ 100% ownership.',
    fullDefinitionAr: 'Free Zones (DIFC، DMCC، IFZA): 0% corporate tax (لـ qualifying)، 100% foreign ownership، repatriation كامل. مكلفة لكن مرنة.',
    category: 'legal',
    relatedTerms: ['mainland', 'incorporation'],
    keywords: ['free zone', 'منطقة حرة', 'UAE'],
  },
  {
    slug: 'flat6labs',
    termAr: 'Flat6Labs',
    termEn: 'Flat6Labs',
    shortDefinitionAr: 'أكبر حاضنة ستارت أبس في المنطقة العربية.',
    fullDefinitionAr: 'Flat6Labs أسستها AUC في 2011. تحضن أكثر من 300 startup عبر Cairo، Riyadh، Beirut، Tunis، Manama، Abu Dhabi.',
    category: 'fundraising',
    relatedTerms: ['accelerator', 'incubator'],
    keywords: ['Flat6Labs', 'حاضنة', 'incubator'],
  },
  {
    slug: 'accelerator',
    termAr: 'Accelerator (مسرعة الأعمال)',
    termEn: 'Accelerator',
    shortDefinitionAr: 'برنامج 3-6 شهور يقدم دعم وتمويل صغير ومرشدين للستارت أبس.',
    fullDefinitionAr: 'Accelerators (YC، Techstars، 500): cohort-based، 3-6 شهور، investment $50-150K مقابل 6-10%، demo day في النهاية.',
    category: 'fundraising',
    relatedTerms: ['incubator', 'flat6labs'],
    keywords: ['accelerator', 'مسرعة', 'YC'],
  },
  {
    slug: 'pre-money',
    termAr: 'Pre-Money / Post-Money Valuation',
    termEn: 'Pre/Post Money Valuation',
    shortDefinitionAr: 'Pre-money = قيمة الشركة قبل الاستثمار. Post-money = بعده.',
    fullDefinitionAr: 'Post-money = Pre-money + Investment. مثال: $5M pre + $1M = $6M post. Investor gets 1/6 = 16.67%. مهم للـ negotiation.',
    category: 'fundraising',
    relatedTerms: ['valuation', 'dilution'],
    keywords: ['pre-money', 'valuation', 'تقييم'],
  },
  {
    slug: 'term-sheet',
    termAr: 'Term Sheet (ورقة الشروط)',
    termEn: 'Term Sheet',
    shortDefinitionAr: 'وثيقة non-binding تحدد شروط الاستثمار قبل الـ legal docs.',
    fullDefinitionAr: 'Term sheet يحدد: valuation، investment amount، board seats، liquidation preference، anti-dilution. تفاوض كل clause بعناية.',
    category: 'fundraising',
    relatedTerms: ['negotiation', 'series-a'],
    keywords: ['term sheet', 'ورقة شروط'],
  },
  {
    slug: 'liquidation-preference',
    termAr: 'Liquidation Preference',
    termEn: 'Liquidation Preference',
    shortDefinitionAr: 'حق المستثمر في استرداد استثماره أولاً عند البيع.',
    fullDefinitionAr: '1× non-participating = standard. 2× participating = aggressive. يحدد كم يحصل المستثمر vs المؤسسون في scenarios مختلفة.',
    category: 'fundraising',
    relatedTerms: ['term-sheet', 'exit'],
    keywords: ['liquidation preference', 'تفضيل التصفية'],
  },
  {
    slug: 'arpu-vs-arppu',
    termAr: 'ARPU vs ARPPU',
    termEn: 'ARPU vs ARPPU',
    shortDefinitionAr: 'ARPU = كل المستخدمين. ARPPU = المستخدمون الدافعون فقط.',
    fullDefinitionAr: 'مهم في freemium. ARPPU عادة أعلى بكثير من ARPU. مثال: ARPU $1، ARPPU $20 (5% conversion).',
    category: 'finance',
    relatedTerms: ['arpu', 'freemium'],
    keywords: ['ARPU', 'ARPPU', 'متوسط الإيراد'],
  },
  {
    slug: 'freemium',
    termAr: 'Freemium',
    termEn: 'Freemium',
    shortDefinitionAr: 'نموذج تجاري: نسخة مجانية + نسخة paid premium.',
    fullDefinitionAr: 'Freemium يقلل CAC ويزيد funnel، لكنه مكلف (الـ free users يستخدمون resources). مثال: Spotify، Dropbox، Slack.',
    category: 'marketing',
    relatedTerms: ['plg', 'self-serve'],
    keywords: ['freemium', 'مجاني', 'subscription'],
  },
  {
    slug: 'cohort-analysis',
    termAr: 'Cohort Analysis',
    termEn: 'Cohort Analysis',
    shortDefinitionAr: 'تحليل المستخدمين بحسب فترة انضمامهم لرصد retention.',
    fullDefinitionAr: 'Cohorts عادة شهرية. تكشف هل التحسينات في retention حقيقية أم noise. أداة أساسية لـ growth teams.',
    category: 'product',
    relatedTerms: ['retention', 'churn'],
    keywords: ['cohort', 'analysis', 'retention'],
  },
  {
    slug: 'customer-success',
    termAr: 'Customer Success',
    termEn: 'Customer Success',
    shortDefinitionAr: 'فريق يضمن نجاح العملاء بمنتجك، يقلل churn، يزيد expansion.',
    fullDefinitionAr: 'CS != Support. CS proactive، strategic، يدفع expansion. أهم metrics: NRR، GRR، health score، CSAT.',
    category: 'sales',
    relatedTerms: ['nrr', 'churn'],
    keywords: ['customer success', 'CS', 'CSM'],
  },
  {
    slug: 'lean-startup',
    termAr: 'Lean Startup',
    termEn: 'Lean Startup',
    shortDefinitionAr: 'منهجية Eric Ries: Build-Measure-Learn loops سريعة لتجنب الـ waste.',
    fullDefinitionAr: 'Lean Startup يعتمد على: MVP، validated learning، pivots. تجنب building features لا أحد يريدها. كتاب أساسي لكل founder.',
    category: 'product',
    relatedTerms: ['mvp', 'pivot'],
    keywords: ['lean startup', 'eric ries', 'methodology'],
  },
  {
    slug: 'pivot',
    termAr: 'Pivot (التحول الاستراتيجي)',
    termEn: 'Pivot',
    shortDefinitionAr: 'تغيير في الاستراتيجية مع الحفاظ على بعض الـ learnings.',
    fullDefinitionAr: 'Pivot ليست فشل - هي تطور. Slack بدأت كـ game. Instagram بدأت كـ check-in app. اختر الـ pivot بعد بيانات، ليس بعد yatak.',
    category: 'product',
    relatedTerms: ['lean-startup', 'pmf'],
    keywords: ['pivot', 'تحول', 'strategy'],
  },
  {
    slug: 'stakeholder',
    termAr: 'Stakeholder (أصحاب المصلحة)',
    termEn: 'Stakeholder',
    shortDefinitionAr: 'كل من يتأثر أو يؤثر في شركتك: موظفين، عملاء، مستثمرين، شركاء.',
    fullDefinitionAr: 'Stakeholder management مهارة أساسية للـ founder. كل decision يجب أن يأخذ في الاعتبار impact على stakeholders المختلفين.',
    category: 'fundraising',
    relatedTerms: ['investor', 'employee'],
    keywords: ['stakeholder', 'أصحاب مصلحة'],
  },
  {
    slug: 'agile',
    termAr: 'Agile (المنهجية الرشيقة)',
    termEn: 'Agile',
    shortDefinitionAr: 'منهجية تطوير برمجيات تعتمد على iterations قصيرة وflexibility.',
    fullDefinitionAr: 'Agile (Scrum، Kanban) يقسم العمل لـ sprints قصيرة (1-4 أسبوع). يفضل working software على documentation. سائد في tech.',
    category: 'product',
    relatedTerms: ['scrum', 'sprint'],
    keywords: ['agile', 'scrum', 'methodology'],
  },
  {
    slug: 'sprint',
    termAr: 'Sprint',
    termEn: 'Sprint',
    shortDefinitionAr: 'فترة عمل قصيرة (عادة 2 أسبوع) في منهجية Agile.',
    fullDefinitionAr: 'Sprint له: planning، daily standups، work، review، retrospective. هدفه shipping قطعة محددة من القيمة.',
    category: 'product',
    relatedTerms: ['agile', 'scrum'],
    keywords: ['sprint', 'agile', 'scrum'],
  },
  {
    slug: 'okr',
    termAr: 'OKR (Objectives and Key Results)',
    termEn: 'OKR',
    shortDefinitionAr: 'إطار goal setting شائع في Google: Objective + 3-5 measurable Key Results.',
    fullDefinitionAr: 'OKRs ربع سنوية. Objective = طموح. KRs = measurable. Score 0.0-1.0. 0.7 = success. > 0.9 = الهدف ضعيف. شفافة across الشركة.',
    category: 'product',
    relatedTerms: ['kpi', 'goal-setting'],
    keywords: ['OKR', 'objectives', 'goals'],
  },
  {
    slug: 'a-b-test',
    termAr: 'A/B Test (الاختبار المقارن)',
    termEn: 'A/B Test',
    shortDefinitionAr: 'تجربة نسختين من شيء (UI، email، إلخ) لمعرفة الأفضل بإحصائيات.',
    fullDefinitionAr: 'A/B testing يحتاج: hypothesis، sample size، statistical significance (p < 0.05). أدوات: Optimizely، VWO، Statsig.',
    category: 'product',
    relatedTerms: ['experiment', 'analytics'],
    keywords: ['A/B test', 'اختبار', 'optimization'],
  },
];

export function getGlossaryTermBySlug(slug: string): GlossaryTerm | undefined {
  return GLOSSARY.find((t) => t.slug === slug);
}

export function getAllGlossarySlugs(): string[] {
  return GLOSSARY.map((t) => t.slug);
}

export function getGlossaryByCategory(category: GlossaryTerm['category']): GlossaryTerm[] {
  return GLOSSARY.filter((t) => t.category === category);
}
