/**
 * Programmatic SEO — Industries.
 * Pages: /industries/[slug]
 */

export interface Industry {
  slug: string;
  nameAr: string;
  nameEn: string;
  metaDescriptionAr: string;
  metaDescriptionEn: string;
  heroIntroAr: string;
  marketSizeAr: string;
  growthRateAr: string;
  topAgents: string[];
  challenges: string[];
  opportunities: string[];
  caseStudies: { title: string; outcome: string }[];
  relatedUseCaseSlugs: string[];
  keywords: string[];
}

export const INDUSTRIES: Industry[] = [
  {
    slug: 'fintech',
    nameAr: 'الفنتك',
    nameEn: 'Fintech',
    metaDescriptionAr: 'كلميرون للفنتك: حلول AI متخصصة لشركات التكنولوجيا المالية في مصر والمنطقة العربية.',
    metaDescriptionEn: 'Kalmeron for Fintech: specialized AI solutions for financial technology companies in MENA.',
    heroIntroAr: 'الفنتك في المنطقة العربية يجذب 40% من تمويل الستارت أبس. كلميرون يفهم التراخيص، الامتثال، والتكامل مع البنية المالية المحلية.',
    marketSizeAr: '$3.5 مليار في مصر بحلول 2026',
    growthRateAr: '32% سنوياً',
    topAgents: ['legal_guide', 'compliance', 'cfo_agent', 'opportunity_radar'],
    challenges: ['التراخيص الصارمة من البنك المركزي', 'الامتثال (KYC/AML)', 'بناء الثقة', 'المنافسة من البنوك التقليدية'],
    opportunities: ['Underbanked population كبيرة', 'دعم حكومي', 'BNPL في نمو سريع', 'قطاع التحويلات الضخم'],
    caseStudies: [
      { title: 'منصة BNPL في مصر', outcome: 'وصلت 50K مستخدم في 6 شهور بدعم استراتيجية كلميرون' },
      { title: 'محفظة إلكترونية للقطاع غير المصرفي', outcome: 'حصلت على ترخيص في 4 شهور' },
    ],
    relatedUseCaseSlugs: ['launch-fintech-app', 'raise-seed-funding'],
    keywords: ['fintech', 'فنتك', 'تكنولوجيا مالية', 'محفظة إلكترونية', 'BNPL'],
  },
  {
    slug: 'ecommerce',
    nameAr: 'التجارة الإلكترونية',
    nameEn: 'E-commerce',
    metaDescriptionAr: 'كلميرون للتجارة الإلكترونية: من اختيار المنتج إلى التحجيم. كل ما تحتاجه لبناء متجر ناجح.',
    metaDescriptionEn: 'Kalmeron for E-commerce: from product selection to scaling. Build a successful online store.',
    heroIntroAr: 'سوق التجارة الإلكترونية في مصر $9 مليار وينمو 25% سنوياً. كلميرون يساعدك في كل خطوة من الفكرة للتحجيم.',
    marketSizeAr: '$9 مليار في مصر، $50 مليار في MENA',
    growthRateAr: '25% سنوياً',
    topAgents: ['marketing_orchestrator', 'cfo_agent', 'idea_validator', 'opportunity_radar'],
    challenges: ['ارتفاع تكلفة الاستحواذ', 'مشاكل التوصيل', 'الدفع عند الاستلام (COD)', 'العائدات العالية'],
    opportunities: ['نمو سريع', 'انتشار الـ smartphones', 'تطور البنية اللوجستية', 'فرص الـ niches'],
    caseStudies: [
      { title: 'متجر منتجات صحية', outcome: 'وصل لـ $500K مبيعات في السنة الأولى' },
      { title: 'D2C fashion brand', outcome: 'انخفض CAC بنسبة 40%' },
    ],
    relatedUseCaseSlugs: ['build-ecommerce-store', 'pricing-strategy', 'build-content-marketing'],
    keywords: ['تجارة إلكترونية', 'متجر إلكتروني', 'ecommerce', 'shopify', 'دروب شيبينغ'],
  },
  {
    slug: 'saas',
    nameAr: 'البرمجيات كخدمة',
    nameEn: 'SaaS',
    metaDescriptionAr: 'كلميرون لشركات SaaS: من تحقق الفكرة إلى MRR متنامي. كل شيء تحتاجه لبناء SaaS ناجح.',
    metaDescriptionEn: 'Kalmeron for SaaS: from idea validation to growing MRR. Build a successful SaaS company.',
    heroIntroAr: 'SaaS قطاع يضاعف نفسه كل 3 سنوات في المنطقة. كلميرون يبني معك من الفكرة إلى الإطلاق إلى التحجيم.',
    marketSizeAr: '$1.5 مليار في MENA',
    growthRateAr: '30% سنوياً',
    topAgents: ['idea_validator', 'plan_builder', 'marketing_orchestrator', 'cfo_agent'],
    challenges: ['Product-Market Fit', 'تخفيض الـ Churn', 'استراتيجية التسعير', 'البيع B2B'],
    opportunities: ['Scaling عالمياً', 'Recurring revenue', 'High margins', 'Defensibility'],
    caseStudies: [
      { title: 'CRM للسوق المصري', outcome: 'وصل لـ 1000 عميل مدفوع في 18 شهر' },
      { title: 'منصة HR للشركات الصغيرة', outcome: 'حقق $500K ARR في السنة الأولى' },
    ],
    relatedUseCaseSlugs: ['validate-saas-idea', 'build-mvp-30-days', 'pricing-strategy'],
    keywords: ['SaaS', 'برمجيات كخدمة', 'subscription', 'B2B software'],
  },
  {
    slug: 'food-beverage',
    nameAr: 'الطعام والمشروبات',
    nameEn: 'Food & Beverage',
    metaDescriptionAr: 'كلميرون لقطاع الطعام: مطاعم، مطابخ سحابية، علامات FMCG. خبرة محلية متعمقة.',
    metaDescriptionEn: 'Kalmeron for F&B: restaurants, cloud kitchens, FMCG brands. Deep local expertise.',
    heroIntroAr: 'قطاع الطعام في مصر $40 مليار. مطاعم وعلامات FMCG ومطابخ سحابية. كلميرون يفهم تحديات كل نموذج.',
    marketSizeAr: '$40 مليار في مصر',
    growthRateAr: '12% سنوياً',
    topAgents: ['idea_validator', 'cfo_agent', 'legal_guide', 'marketing_orchestrator'],
    challenges: ['الاعتماد على الموردين', 'هامش ربح ضيق', 'تقلبات الأسعار', 'صعوبة التوسع'],
    opportunities: ['نمو طلب التوصيل', 'منتجات صحية', 'مطابخ سحابية low-CapEx', 'علامات D2C'],
    caseStudies: [
      { title: 'مطعم سحابي للأكل الصحي', outcome: 'افتتح 5 فروع في سنة' },
      { title: 'علامة قهوة محلية', outcome: 'دخلت 3 سلاسل سوبر ماركت' },
    ],
    relatedUseCaseSlugs: ['launch-cloud-restaurant'],
    keywords: ['مطعم', 'مطبخ سحابي', 'F&B', 'طعام', 'cloud kitchen'],
  },
  {
    slug: 'logistics',
    nameAr: 'اللوجستيات والشحن',
    nameEn: 'Logistics',
    metaDescriptionAr: 'كلميرون لشركات اللوجستيات: من last-mile إلى freight forwarding.',
    metaDescriptionEn: 'Kalmeron for Logistics: from last-mile to freight forwarding.',
    heroIntroAr: 'اللوجستيات في المنطقة قطاع $25 مليار. كلميرون يخطط لك التشغيل، التسعير، والشراكات.',
    marketSizeAr: '$25 مليار في MENA',
    growthRateAr: '14% سنوياً',
    topAgents: ['cfo_agent', 'idea_validator', 'marketing_orchestrator'],
    challenges: ['Capital-intensive', 'هامش ربح ضيق', 'إدارة الأسطول', 'العملاء الكبار يفرضون شروط صعبة'],
    opportunities: ['نمو ecommerce', 'الـ COD يخلق فرص', 'الـ B2B logistics underserved'],
    caseStudies: [
      { title: 'شركة last-mile delivery', outcome: 'وصلت لـ 200 طلبية يومياً' },
    ],
    relatedUseCaseSlugs: ['build-ecommerce-store'],
    keywords: ['logistics', 'لوجستيات', 'شحن', 'توصيل'],
  },
  {
    slug: 'agritech',
    nameAr: 'التكنولوجيا الزراعية',
    nameEn: 'AgriTech',
    metaDescriptionAr: 'كلميرون للتكنولوجيا الزراعية: حلول للمزارعين، السلاسل، والتمويل الزراعي.',
    metaDescriptionEn: 'Kalmeron for AgriTech: solutions for farmers, supply chains, and agricultural finance.',
    heroIntroAr: 'الزراعة 11% من اقتصاد مصر. AgriTech قطاع underserved مع فرص ضخمة. كلميرون يفهم تحديات المزارع المصري.',
    marketSizeAr: '$500M في مصر',
    growthRateAr: '20% سنوياً',
    topAgents: ['idea_validator', 'cfo_agent', 'opportunity_radar'],
    challenges: ['Adoption بطيء', 'البنية التحتية الريفية', 'مقاومة التغيير', 'تمويل المزارعين'],
    opportunities: ['دعم حكومي قوي', 'فجوة بين الإنتاج والاستهلاك', 'الـ export markets'],
    caseStudies: [
      { title: 'منصة ربط مزارعين بمشترين', outcome: '10K مزارع مسجل' },
    ],
    relatedUseCaseSlugs: [],
    keywords: ['agritech', 'تكنولوجيا زراعية', 'زراعة ذكية'],
  },
  {
    slug: 'edtech',
    nameAr: 'التكنولوجيا التعليمية',
    nameEn: 'EdTech',
    metaDescriptionAr: 'كلميرون للتعليم الإلكتروني: من K-12 إلى التدريب المهني. حلول لكل مرحلة.',
    metaDescriptionEn: 'Kalmeron for EdTech: from K-12 to professional training. Solutions for every stage.',
    heroIntroAr: 'EdTech العربي $7B. الفجوة بين الطلب والعرض ضخمة. كلميرون يبني معك منتج تعليمي بمعايير عالمية.',
    marketSizeAr: '$7B في MENA',
    growthRateAr: '28% سنوياً',
    topAgents: ['idea_validator', 'plan_builder', 'marketing_orchestrator'],
    challenges: ['الدفع من الأهل', 'جودة المحتوى', 'الـ engagement', 'B2G المعقد'],
    opportunities: ['Vision 2030 يضخ مليارات', 'الأهل مستعدون يدفعون', 'Hybrid learning'],
    caseStudies: [
      { title: 'منصة k-12 سعودية', outcome: '500K طالب مسجل في 18 شهر' },
      { title: 'منصة مهارات', outcome: '$3M ARR' },
    ],
    relatedUseCaseSlugs: ['launch-edtech-platform'],
    keywords: ['edtech', 'تعليم إلكتروني', 'منصات تعليمية', 'k-12'],
  },
  {
    slug: 'healthtech',
    nameAr: 'التكنولوجيا الصحية',
    nameEn: 'HealthTech',
    metaDescriptionAr: 'كلميرون للصحة الرقمية: telemedicine، EHR، insurtech، وحلول للمستشفيات.',
    metaDescriptionEn: 'Kalmeron for digital health: telemedicine, EHR, insurtech, hospital solutions.',
    heroIntroAr: 'القطاع الصحي في تحول رقمي عميق. كلميرون يفهم التراخيص والـ trust building.',
    marketSizeAr: '$2B في مصر',
    growthRateAr: '40% سنوياً',
    topAgents: ['legal_guide', 'compliance', 'idea_validator', 'marketing_orchestrator'],
    challenges: ['الموافقات الحكومية', 'الـ trust', 'تكامل المستشفيات', 'الـ insurance integrations'],
    opportunities: ['نقص الأطباء', 'صعود التأمين الصحي', 'دعم حكومي'],
    caseStudies: [
      { title: 'منصة استشارات طبية', outcome: '100K استشارة في السنة الأولى' },
    ],
    relatedUseCaseSlugs: ['launch-healthtech-app'],
    keywords: ['healthtech', 'صحة رقمية', 'telemedicine', 'EHR'],
  },
  {
    slug: 'foodtech',
    nameAr: 'تكنولوجيا الطعام',
    nameEn: 'FoodTech',
    metaDescriptionAr: 'كلميرون لقطاع الطعام: cloud kitchens، delivery، supply chain، وbrands.',
    metaDescriptionEn: 'Kalmeron for food sector: cloud kitchens, delivery, supply chain, and brands.',
    heroIntroAr: 'سوق الطعام في مصر ضخم وغير منظم. كلميرون يساعدك تبني عمليات احترافية.',
    marketSizeAr: '$15B في مصر',
    growthRateAr: '12% سنوياً',
    topAgents: ['cfo_agent', 'idea_validator', 'marketing_orchestrator', 'opportunity_radar'],
    challenges: ['Margins ضعيفة', 'Delivery costs', 'Food safety', 'Talent shortage'],
    opportunities: ['Cloud kitchens', 'D2C food brands', 'Healthy food trend'],
    caseStudies: [
      { title: 'سلسلة cloud kitchens', outcome: '15 موقع في 24 شهر' },
    ],
    relatedUseCaseSlugs: ['launch-cloud-restaurant'],
    keywords: ['foodtech', 'طعام', 'cloud kitchen', 'food delivery'],
  },
  {
    slug: 'proptech',
    nameAr: 'تكنولوجيا العقارات',
    nameEn: 'PropTech',
    metaDescriptionAr: 'كلميرون للعقارات: marketplaces، property management، وأدوات تقييم.',
    metaDescriptionEn: 'Kalmeron for real estate: marketplaces, property management, valuation tools.',
    heroIntroAr: 'سوق العقارات المصري $50B. PropTech بدأ يكسر السوق التقليدي. كلميرون يبني معك.',
    marketSizeAr: '$50B في مصر',
    growthRateAr: '15% سنوياً',
    topAgents: ['idea_validator', 'cfo_agent', 'marketing_orchestrator'],
    challenges: ['ثقافة المتعاملين', 'البيانات غير منظمة', 'commission structures'],
    opportunities: ['Egypt 2030 projects', 'New cairo developments', 'Vacation rentals'],
    caseStudies: [
      { title: 'منصة عقارية', outcome: '$10M GMV في السنة الأولى' },
    ],
    relatedUseCaseSlugs: ['build-marketplace'],
    keywords: ['proptech', 'عقارات', 'real estate'],
  },
  {
    slug: 'media-entertainment',
    nameAr: 'الإعلام والترفيه',
    nameEn: 'Media & Entertainment',
    metaDescriptionAr: 'كلميرون لقطاع الإعلام: streaming، podcasts، gaming، وcontent creation.',
    metaDescriptionEn: 'Kalmeron for media: streaming, podcasts, gaming, and content creation.',
    heroIntroAr: 'المحتوى العربي under-served. الفرص للـ streaming والـ podcasts والـ gaming ضخمة.',
    marketSizeAr: '$5B في MENA',
    growthRateAr: '22% سنوياً',
    topAgents: ['marketing_orchestrator', 'idea_validator', 'plan_builder'],
    challenges: ['Content costs', 'Piracy', 'Monetization حساسة'],
    opportunities: ['Demand للـ Arabic content', 'Gaming market نمو سريع', 'Creator economy'],
    caseStudies: [
      { title: 'منصة محتوى عربي', outcome: '5M users في 24 شهر' },
    ],
    relatedUseCaseSlugs: ['launch-podcast-business'],
    keywords: ['media', 'streaming', 'gaming', 'creator economy'],
  },
  {
    slug: 'cybersecurity',
    nameAr: 'الأمن السيبراني',
    nameEn: 'Cybersecurity',
    metaDescriptionAr: 'كلميرون للأمن السيبراني: حلول للستارت أبس، المؤسسات، والحكومات.',
    metaDescriptionEn: 'Kalmeron for cybersecurity: solutions for startups, enterprises, governments.',
    heroIntroAr: 'الأمن السيبراني الأقل تشبعاً في المنطقة. الطلب يتجاوز العرض بـ 5×.',
    marketSizeAr: '$1.2B في MENA',
    growthRateAr: '25% سنوياً',
    topAgents: ['compliance', 'legal_guide', 'plan_builder'],
    challenges: ['Talent gap', 'Awareness ضعيف', 'Long sales cycles'],
    opportunities: ['Vision 2030 يستثمر', 'مؤسسات مرعوبة', 'Government مُلزِم'],
    caseStudies: [
      { title: 'منصة SOC للبنوك', outcome: '5 بنوك مصرية موقعة' },
    ],
    relatedUseCaseSlugs: ['build-b2b-saas'],
    keywords: ['cybersecurity', 'أمن سيبراني', 'security'],
  },
  {
    slug: 'climate-tech',
    nameAr: 'تكنولوجيا المناخ',
    nameEn: 'Climate Tech',
    metaDescriptionAr: 'كلميرون لـ climate tech: حلول الطاقة المتجددة، carbon، وsustainability.',
    metaDescriptionEn: 'Kalmeron for climate tech: renewable energy, carbon, sustainability solutions.',
    heroIntroAr: 'موجة climate-tech بدأت تصل المنطقة. كلميرون يساعدك تبني حلول مع تمويل سهل.',
    marketSizeAr: '$3B في MENA حتى 2030',
    growthRateAr: '50% سنوياً',
    topAgents: ['idea_validator', 'cfo_agent', 'opportunity_radar'],
    challenges: ['CapEx عالي', 'Long ROI', 'Regulation معقد'],
    opportunities: ['دعم حكومي ضخم', 'Carbon credits', 'ESG mandates'],
    caseStudies: [
      { title: 'شركة solar', outcome: '$5M في tax credits' },
    ],
    relatedUseCaseSlugs: [],
    keywords: ['climate', 'مناخ', 'renewable', 'sustainability'],
  },
  {
    slug: 'mobility-transportation',
    nameAr: 'التنقل والنقل',
    nameEn: 'Mobility & Transportation',
    metaDescriptionAr: 'كلميرون لقطاع التنقل: ride-hailing، EVs، logistics، وmobility-as-a-service.',
    metaDescriptionEn: 'Kalmeron for mobility: ride-hailing, EVs, logistics, mobility-as-a-service.',
    heroIntroAr: 'قطاع المواصلات ينقلب. كلميرون يساعدك تستفيد من التحول.',
    marketSizeAr: '$8B في مصر',
    growthRateAr: '18% سنوياً',
    topAgents: ['idea_validator', 'cfo_agent', 'opportunity_radar'],
    challenges: ['Capital intensive', 'Regulation', 'Driver economics'],
    opportunities: ['EV adoption', 'Underserved cities', 'B2B fleets'],
    caseStudies: [
      { title: 'app توصيل بالموتسيكل', outcome: '$8M Series A' },
    ],
    relatedUseCaseSlugs: [],
    keywords: ['mobility', 'transportation', 'ride-hailing', 'EV'],
  },
  {
    slug: 'creator-economy',
    nameAr: 'اقتصاد المبدعين',
    nameEn: 'Creator Economy',
    metaDescriptionAr: 'كلميرون لاقتصاد المبدعين: tools، monetization، وbrand deals.',
    metaDescriptionEn: 'Kalmeron for creator economy: tools, monetization, and brand deals.',
    heroIntroAr: '500K+ creators في مصر. السوق ينمو 40% سنوياً. كلميرون يبنيلك أدوات.',
    marketSizeAr: '$1B في MENA',
    growthRateAr: '40% سنوياً',
    topAgents: ['marketing_orchestrator', 'idea_validator', 'plan_builder'],
    challenges: ['Monetization صعبة', 'Platform dependence', 'Burnout'],
    opportunities: ['Creator tools tail', 'B2B for creators', 'Community products'],
    caseStudies: [
      { title: 'منصة LinkInBio عربية', outcome: '50K creators في سنة' },
    ],
    relatedUseCaseSlugs: ['build-personal-brand', 'launch-podcast-business'],
    keywords: ['creator economy', 'مبدعين', 'creators', 'influencers'],
  },
  {
    slug: 'manufacturing',
    nameAr: 'التصنيع',
    nameEn: 'Manufacturing',
    metaDescriptionAr: 'كلميرون للتصنيع: digital transformation، industry 4.0، وsupply chain.',
    metaDescriptionEn: 'Kalmeron for manufacturing: digital transformation, industry 4.0, supply chain.',
    heroIntroAr: 'التصنيع المصري 17% من GDP. التحول الرقمي للمصانع فرصة كبرى.',
    marketSizeAr: '$60B في مصر',
    growthRateAr: '8% سنوياً',
    topAgents: ['idea_validator', 'cfo_agent', 'compliance'],
    challenges: ['Capital costs', 'Workforce training', 'Energy costs'],
    opportunities: ['Localization initiative', 'Export incentives', 'Industry 4.0'],
    caseStudies: [
      { title: 'مصنع عبوات', outcome: 'EBITDA +30% بعد ERP' },
    ],
    relatedUseCaseSlugs: [],
    keywords: ['manufacturing', 'تصنيع', 'industry 4.0'],
  },
  {
    slug: 'tourism-hospitality',
    nameAr: 'السياحة والضيافة',
    nameEn: 'Tourism & Hospitality',
    metaDescriptionAr: 'كلميرون للسياحة: hotels، tour operators، experiences، وbooking.',
    metaDescriptionEn: 'Kalmeron for tourism: hotels, tour operators, experiences, booking.',
    heroIntroAr: 'السياحة المصرية في انتعاش. الفرص في tech مع 14M زائر سنوياً.',
    marketSizeAr: '$13B في مصر',
    growthRateAr: '11% سنوياً',
    topAgents: ['marketing_orchestrator', 'idea_validator', 'cfo_agent'],
    challenges: ['Seasonality', 'Currency volatility', 'Online presence ضعيف'],
    opportunities: ['Vision 2030 KSA', 'NEOM', 'Egypt expansion'],
    caseStudies: [
      { title: 'منصة tour booking', outcome: '$2M GMV في السنة الأولى' },
    ],
    relatedUseCaseSlugs: [],
    keywords: ['tourism', 'سياحة', 'hospitality', 'travel'],
  },
  {
    slug: 'professional-services',
    nameAr: 'الخدمات المهنية',
    nameEn: 'Professional Services',
    metaDescriptionAr: 'كلميرون للخدمات المهنية: consulting، agencies، law firms، وaccounting.',
    metaDescriptionEn: 'Kalmeron for professional services: consulting, agencies, law firms, accounting.',
    heroIntroAr: 'الخدمات المهنية تحتاج أتمتة عميقة. كلميرون يبنيلك ops احترافية.',
    marketSizeAr: '$8B في MENA',
    growthRateAr: '12% سنوياً',
    topAgents: ['plan_builder', 'cfo_agent', 'marketing_orchestrator'],
    challenges: ['Talent retention', 'Project margins', 'Sales cycles'],
    opportunities: ['AI for services', 'Productized services', 'Subscription models'],
    caseStudies: [
      { title: 'agency تسويق', outcome: '$1M ARR في 24 شهر' },
    ],
    relatedUseCaseSlugs: [],
    keywords: ['professional services', 'consulting', 'agencies'],
  },
  {
    slug: 'web3-blockchain',
    nameAr: 'Web3 والـ Blockchain',
    nameEn: 'Web3 & Blockchain',
    metaDescriptionAr: 'كلميرون للـ Web3: crypto، DeFi، NFTs، blockchain solutions.',
    metaDescriptionEn: 'Kalmeron for Web3: crypto, DeFi, NFTs, blockchain solutions.',
    heroIntroAr: 'Web3 في المنطقة في مرحلة بناء. الفرص للـ first movers ضخمة.',
    marketSizeAr: '$500M في MENA',
    growthRateAr: '60% سنوياً',
    topAgents: ['legal_guide', 'compliance', 'idea_validator'],
    challenges: ['Regulation غير واضح', 'Talent scarcity', 'Trust issues'],
    opportunities: ['Dubai pro-crypto', 'Gaming + NFT', 'Cross-border payments'],
    caseStudies: [
      { title: 'منصة Web3 إماراتية', outcome: '$10M Series A' },
    ],
    relatedUseCaseSlugs: [],
    keywords: ['web3', 'blockchain', 'crypto', 'DeFi'],
  },
  {
    slug: 'sportstech',
    nameAr: 'تكنولوجيا الرياضة',
    nameEn: 'SportsTech',
    metaDescriptionAr: 'كلميرون لقطاع الرياضة: fan engagement، fitness، analytics، وbetting.',
    metaDescriptionEn: 'Kalmeron for sports: fan engagement, fitness, analytics, betting.',
    heroIntroAr: 'الرياضة بالمنطقة passion. الفرص في tech تنمو مع Vision 2030.',
    marketSizeAr: '$2B في MENA',
    growthRateAr: '20% سنوياً',
    topAgents: ['marketing_orchestrator', 'idea_validator', 'plan_builder'],
    challenges: ['Federation deals', 'Long sales cycles', 'Platform dependence'],
    opportunities: ['LIV Golf، NEOM المرور', 'Fan engagement', 'Fitness apps'],
    caseStudies: [
      { title: 'fitness app إماراتي', outcome: '500K MAU' },
    ],
    relatedUseCaseSlugs: [],
    keywords: ['sportstech', 'رياضة', 'fitness', 'fan engagement'],
  },
];

export function getIndustryBySlug(slug: string): Industry | undefined {
  return INDUSTRIES.find((i) => i.slug === slug);
}

export function getAllIndustrySlugs(): string[] {
  return INDUSTRIES.map((i) => i.slug);
}
