/**
 * Programmatic SEO — Templates Library.
 * Pages: /templates and /templates/[slug]
 */

export interface SeoTemplate {
  slug: string;
  titleAr: string;
  titleEn: string;
  metaDescriptionAr: string;
  metaDescriptionEn: string;
  category:
    | 'business-plan'
    | 'financial-model'
    | 'pitch-deck'
    | 'legal'
    | 'marketing'
    | 'sales'
    | 'hr'
    | 'operations';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  format: 'docx' | 'xlsx' | 'pdf' | 'pptx' | 'notion' | 'figma';
  estimatedTimeMinutes: number;
  agentSlug: string;
  sections: { title: string; description: string }[];
  outcomes: string[];
  keywords: string[];
}

export const TEMPLATES: SeoTemplate[] = [
  {
    slug: 'business-plan-egypt',
    titleAr: 'خطة عمل احترافية للسوق المصري',
    titleEn: 'Professional Business Plan for Egypt',
    metaDescriptionAr: 'قالب خطة عمل بمعايير البنوك والمستثمرين، مخصص للسوق المصري مع كل الأقسام المطلوبة.',
    metaDescriptionEn: 'Bank-grade business plan template tailored for Egypt market with all required sections.',
    category: 'business-plan',
    difficulty: 'intermediate',
    format: 'docx',
    estimatedTimeMinutes: 90,
    agentSlug: 'plan_builder',
    sections: [
      { title: 'الملخص التنفيذي', description: '2-3 صفحات تلخص المشروع كاملاً.' },
      { title: 'وصف الشركة', description: 'الرؤية، الرسالة، الهيكل القانوني.' },
      { title: 'تحليل السوق', description: 'حجم السوق، الفئة المستهدفة، المنافسون.' },
      { title: 'استراتيجية التسويق', description: 'positioning، channels، budget.' },
      { title: 'العمليات', description: 'Supply chain، locations، technology.' },
      { title: 'النموذج المالي', description: 'P&L، Cash flow، Balance sheet 36 شهراً.' },
      { title: 'تحليل المخاطر', description: 'Top 10 risks مع mitigation.' },
    ],
    outcomes: ['خطة عمل 30+ صفحة', 'نموذج مالي Excel مرفق', 'Pitch deck مساند'],
    keywords: ['خطة عمل', 'business plan', 'دراسة جدوى', 'business plan template'],
  },
  {
    slug: 'pitch-deck-seed',
    titleAr: 'Pitch Deck لجولة Seed',
    titleEn: 'Seed Round Pitch Deck',
    metaDescriptionAr: '12 شريحة pitch deck بمعايير Sequoia، لجمع تمويل seed في المنطقة العربية.',
    metaDescriptionEn: '12-slide Sequoia-standard pitch deck for raising seed funding in MENA.',
    category: 'pitch-deck',
    difficulty: 'intermediate',
    format: 'pptx',
    estimatedTimeMinutes: 120,
    agentSlug: 'cfo_agent',
    sections: [
      { title: 'Vision', description: 'جملة واحدة قوية.' },
      { title: 'Problem', description: 'الألم الذي تحله.' },
      { title: 'Solution', description: 'منتجك.' },
      { title: 'Market', description: 'TAM/SAM/SOM.' },
      { title: 'Product Demo', description: 'screenshots أو video.' },
      { title: 'Traction', description: 'الأرقام التي تثبت PMF.' },
      { title: 'Business Model', description: 'كيف تكسب فلوس.' },
      { title: 'Competition', description: 'لماذا أنت ستفوز.' },
      { title: 'Team', description: 'لماذا أنتم الأنسب.' },
      { title: 'Financials', description: 'Last 12 + next 36 شهر.' },
      { title: 'Ask', description: 'كم تريد ولماذا.' },
      { title: 'Vision (مرة أخرى)', description: 'ختام قوي.' },
    ],
    outcomes: ['Pitch deck جاهز', 'Speaker notes', 'FAQ document'],
    keywords: ['pitch deck', 'seed pitch', 'investor deck'],
  },
  {
    slug: 'financial-model-saas',
    titleAr: 'نموذج مالي لشركات SaaS',
    titleEn: 'SaaS Financial Model',
    metaDescriptionAr: 'نموذج Excel كامل لـ SaaS مع MRR، churn، CAC، LTV، وكل metrics التي يفحصها VCs.',
    metaDescriptionEn: 'Complete Excel SaaS model with MRR, churn, CAC, LTV, and all VC-checked metrics.',
    category: 'financial-model',
    difficulty: 'advanced',
    format: 'xlsx',
    estimatedTimeMinutes: 180,
    agentSlug: 'cfo_agent',
    sections: [
      { title: 'Assumptions', description: 'كل assumption في sheet مستقل.' },
      { title: 'Revenue Build', description: 'Per segment، per pricing tier.' },
      { title: 'Cohort Retention', description: 'Monthly cohorts، 36 شهر.' },
      { title: 'Cost Structure', description: 'COGS، S&M، R&D، G&A.' },
      { title: 'Hiring Plan', description: 'Per role، per quarter.' },
      { title: 'Cash Flow', description: '36 شهر، with covenants.' },
      { title: 'Scenarios', description: 'Base, Upside, Downside.' },
    ],
    outcomes: ['Excel model 10+ sheets', 'Sensitivity analysis', 'Investor-ready'],
    keywords: ['SaaS financial model', 'نموذج مالي', 'MRR model'],
  },
  {
    slug: 'employment-contract-egypt',
    titleAr: 'عقد عمل مصري كامل',
    titleEn: 'Egyptian Employment Contract',
    metaDescriptionAr: 'عقد عمل بقانون العمل المصري الجديد، مع IP assignment وعدم منافسة.',
    metaDescriptionEn: 'Egyptian labor law-compliant contract with IP assignment and non-compete.',
    category: 'legal',
    difficulty: 'beginner',
    format: 'docx',
    estimatedTimeMinutes: 30,
    agentSlug: 'legal_guide',
    sections: [
      { title: 'بيانات الطرفين', description: 'صاحب العمل، الموظف.' },
      { title: 'المنصب والمهام', description: 'Job description تفصيلي.' },
      { title: 'الأجر والمزايا', description: 'الأساسي، البدلات، التأمين.' },
      { title: 'ساعات العمل', description: 'مع مرونة العمل عن بُعد.' },
      { title: 'الإجازات', description: 'سنوية، مرضية، بدون راتب.' },
      { title: 'IP Assignment', description: 'كل ما ينتجه ملك الشركة.' },
      { title: 'NDA', description: 'سرية المعلومات.' },
      { title: 'Non-compete', description: '12 شهر، غير قابل للإنفاذ في كل المهن.' },
      { title: 'إنهاء العقد', description: 'وفقاً لقانون 12/2003.' },
    ],
    outcomes: ['عقد جاهز للتوقيع', 'Compliant مع القانون', 'مرن للتعديل'],
    keywords: ['عقد عمل', 'employment contract', 'قانون العمل المصري'],
  },
  {
    slug: 'nda-template',
    titleAr: 'اتفاقية عدم إفصاح (NDA)',
    titleEn: 'Non-Disclosure Agreement (NDA)',
    metaDescriptionAr: 'NDA بصيغتين: One-way و Mutual، صالحة في مصر والخليج.',
    metaDescriptionEn: 'NDA in two versions: One-way and Mutual, valid in Egypt and GCC.',
    category: 'legal',
    difficulty: 'beginner',
    format: 'docx',
    estimatedTimeMinutes: 15,
    agentSlug: 'legal_guide',
    sections: [
      { title: 'تعريف المعلومات السرية', description: 'تحديد بدقة.' },
      { title: 'التزامات السرية', description: 'مدة، نطاق، استثناءات.' },
      { title: 'مدة الاتفاقية', description: '2-5 سنوات نموذجياً.' },
      { title: 'العقوبات', description: 'تعويضات، injunction.' },
      { title: 'القانون الحاكم', description: 'مصري أو إماراتي.' },
    ],
    outcomes: ['NDA جاهز', 'Two versions', 'Quick to sign'],
    keywords: ['NDA', 'اتفاقية سرية', 'non-disclosure'],
  },
  {
    slug: 'marketing-plan-90-days',
    titleAr: 'خطة تسويق 90 يوم',
    titleEn: '90-Day Marketing Plan',
    metaDescriptionAr: 'قالب خطة تسويق متكاملة للـ 90 يوم القادمة مع Channel mix وKPIs.',
    metaDescriptionEn: '90-day marketing plan template with channel mix and KPIs.',
    category: 'marketing',
    difficulty: 'intermediate',
    format: 'notion',
    estimatedTimeMinutes: 60,
    agentSlug: 'marketing_orchestrator',
    sections: [
      { title: 'Goals & KPIs', description: 'SMART، measurable.' },
      { title: 'ICP & Personas', description: 'تفصيلية.' },
      { title: 'Positioning', description: 'Category، messaging.' },
      { title: 'Channel Strategy', description: 'Paid، organic، PR.' },
      { title: 'Content Calendar', description: 'Weekly themes.' },
      { title: 'Budget Allocation', description: 'Per channel.' },
      { title: 'Measurement', description: 'Weekly review framework.' },
    ],
    outcomes: ['Notion workspace', 'Calendar 90 يوم', 'Budget breakdown'],
    keywords: ['marketing plan', 'خطة تسويق', 'GTM'],
  },
  {
    slug: 'sales-playbook-b2b',
    titleAr: 'Sales Playbook لـ B2B',
    titleEn: 'B2B Sales Playbook',
    metaDescriptionAr: 'دليل sales كامل: discovery، demo، negotiation، closing.',
    metaDescriptionEn: 'Complete sales guide: discovery, demo, negotiation, closing.',
    category: 'sales',
    difficulty: 'advanced',
    format: 'notion',
    estimatedTimeMinutes: 120,
    agentSlug: 'plan_builder',
    sections: [
      { title: 'ICP & Persona', description: 'Detailed scoring.' },
      { title: 'Outbound Sequencing', description: 'Email، LinkedIn، call cadence.' },
      { title: 'Discovery Framework', description: 'BANT، MEDDIC، أو SPIN.' },
      { title: 'Demo Best Practices', description: 'Tell-show-tell.' },
      { title: 'Objection Handling', description: 'Top 20 objections.' },
      { title: 'Negotiation Tactics', description: 'Anchoring، concessions.' },
      { title: 'Closing Techniques', description: 'When to ask، when to wait.' },
    ],
    outcomes: ['Playbook كامل', 'Email templates', 'Demo scripts'],
    keywords: ['sales playbook', 'B2B sales', 'enterprise sales'],
  },
  {
    slug: 'okr-template',
    titleAr: 'قالب OKRs ربع سنوي',
    titleEn: 'Quarterly OKRs Template',
    metaDescriptionAr: 'قالب OKRs على نموذج Google: Objectives + Key Results مع weekly check-ins.',
    metaDescriptionEn: 'Google-style OKRs template: Objectives + Key Results with weekly check-ins.',
    category: 'operations',
    difficulty: 'intermediate',
    format: 'notion',
    estimatedTimeMinutes: 30,
    agentSlug: 'plan_builder',
    sections: [
      { title: 'Company OKRs', description: '3-5 objectives.' },
      { title: 'Department OKRs', description: 'Cascade للأقسام.' },
      { title: 'Individual OKRs', description: '70% department aligned.' },
      { title: 'Weekly Check-ins', description: 'Confidence score 1-5.' },
      { title: 'Quarterly Review', description: 'Score 0.0-1.0.' },
    ],
    outcomes: ['OKR workspace', 'Templates لكل level', 'Review rituals'],
    keywords: ['OKR', 'goal setting', 'objectives'],
  },
  {
    slug: 'investor-update',
    titleAr: 'قالب Update شهري للمستثمرين',
    titleEn: 'Monthly Investor Update Template',
    metaDescriptionAr: 'قالب update شهري بمعايير YC: highlights، metrics، lowlights، asks.',
    metaDescriptionEn: 'YC-style monthly update template: highlights, metrics, lowlights, asks.',
    category: 'pitch-deck',
    difficulty: 'beginner',
    format: 'notion',
    estimatedTimeMinutes: 30,
    agentSlug: 'cfo_agent',
    sections: [
      { title: 'TL;DR', description: '3 sentences.' },
      { title: 'Highlights', description: 'Top wins من الشهر.' },
      { title: 'Lowlights', description: 'صادق عن المشاكل.' },
      { title: 'Key Metrics', description: 'MRR، growth، runway.' },
      { title: 'Customer Stories', description: 'Wins ملموسة.' },
      { title: 'Hiring', description: 'Open roles.' },
      { title: 'Asks', description: 'Specific intros أو help.' },
    ],
    outcomes: ['Template جاهز', 'Examples من شركات حقيقية'],
    keywords: ['investor update', 'monthly update', 'investor relations'],
  },
  {
    slug: 'cap-table',
    titleAr: 'Cap Table احترافي',
    titleEn: 'Professional Cap Table',
    metaDescriptionAr: 'Cap table بمعايير Carta مع scenarios للـ dilution وexit.',
    metaDescriptionEn: 'Carta-grade cap table with dilution and exit scenarios.',
    category: 'financial-model',
    difficulty: 'advanced',
    format: 'xlsx',
    estimatedTimeMinutes: 60,
    agentSlug: 'cfo_agent',
    sections: [
      { title: 'Founders Equity', description: 'Vesting، cliff.' },
      { title: 'ESOP Pool', description: '10-15% reserved.' },
      { title: 'Investor Tranches', description: 'Per round.' },
      { title: 'Convertibles', description: 'SAFEs، notes.' },
      { title: 'Dilution Scenarios', description: 'Pre/post each round.' },
      { title: 'Exit Waterfall', description: 'Liquidation preferences.' },
    ],
    outcomes: ['Cap table Excel', 'Scenarios sheets', 'Visual charts'],
    keywords: ['cap table', 'equity', 'dilution', 'ESOP'],
  },
  {
    slug: 'partnership-agreement',
    titleAr: 'اتفاقية شراكة شاملة',
    titleEn: 'Comprehensive Partnership Agreement',
    metaDescriptionAr: 'عقد شراكة شامل: equity، roles، dispute resolution، exit clauses.',
    metaDescriptionEn: 'Full partnership agreement: equity, roles, dispute resolution, exit clauses.',
    category: 'legal',
    difficulty: 'advanced',
    format: 'docx',
    estimatedTimeMinutes: 60,
    agentSlug: 'legal_guide',
    sections: [
      { title: 'Equity Split', description: 'Initial و vesting.' },
      { title: 'Roles & Responsibilities', description: 'بدقة لكل شريك.' },
      { title: 'Decision Making', description: 'Major vs minor decisions.' },
      { title: 'Compensation', description: 'Salary + equity.' },
      { title: 'Vesting & Cliff', description: '4 years/1 year cliff.' },
      { title: 'Dispute Resolution', description: 'Mediation → arbitration.' },
      { title: 'Exit Scenarios', description: 'Buy-sell، tag-along.' },
    ],
    outcomes: ['عقد شراكة جاهز', 'Custom clauses', 'Lawyer review optional'],
    keywords: ['partnership', 'co-founder agreement', 'shareholder agreement'],
  },
  {
    slug: 'product-requirements-doc',
    titleAr: 'PRD (Product Requirements Document)',
    titleEn: 'Product Requirements Document',
    metaDescriptionAr: 'قالب PRD يستخدم في FAANG لكتابة specs واضحة قبل البناء.',
    metaDescriptionEn: 'FAANG-style PRD template for clear specs before building.',
    category: 'operations',
    difficulty: 'intermediate',
    format: 'notion',
    estimatedTimeMinutes: 45,
    agentSlug: 'plan_builder',
    sections: [
      { title: 'Problem Statement', description: 'الألم بدقة.' },
      { title: 'Goals & Non-Goals', description: 'ما لن نفعله.' },
      { title: 'User Stories', description: 'As a... I want... so that...' },
      { title: 'Solution Design', description: 'Approach + alternatives.' },
      { title: 'Success Metrics', description: 'Measurable.' },
      { title: 'Risks', description: 'Technical، product، business.' },
      { title: 'Timeline', description: 'Milestones.' },
    ],
    outcomes: ['PRD template', 'Examples', 'Review checklist'],
    keywords: ['PRD', 'product spec', 'requirements'],
  },
  {
    slug: 'customer-interview-script',
    titleAr: 'سكريبت مقابلات العملاء',
    titleEn: 'Customer Interview Script',
    metaDescriptionAr: 'دليل The Mom Test في 30 سؤال لمقابلات لا يتلكؤ فيها العميل.',
    metaDescriptionEn: 'Mom Test-style 30-question script that gets honest customer feedback.',
    category: 'operations',
    difficulty: 'beginner',
    format: 'notion',
    estimatedTimeMinutes: 30,
    agentSlug: 'idea_validator',
    sections: [
      { title: 'Warm-up', description: '2-3 أسئلة عامة.' },
      { title: 'Past Behavior', description: 'متى آخر مرة فعلت X؟' },
      { title: 'Current Solutions', description: 'كيف تحل هذا الآن؟' },
      { title: 'Pain Points', description: 'ما الأسوأ؟ كم تكلفك؟' },
      { title: 'Willingness to Pay', description: 'كم تدفع لو وُجد حل؟' },
    ],
    outcomes: ['Script للـ interviews', 'Note-taking template', 'Synthesis framework'],
    keywords: ['customer interview', 'user research', 'مقابلات عملاء'],
  },
  {
    slug: 'go-to-market-canvas',
    titleAr: 'GTM Canvas (نموذج go-to-market)',
    titleEn: 'GTM Canvas',
    metaDescriptionAr: 'Canvas في صفحة واحدة يلخص استراتيجية go-to-market بالكامل.',
    metaDescriptionEn: 'One-page canvas summarizing your full GTM strategy.',
    category: 'marketing',
    difficulty: 'intermediate',
    format: 'figma',
    estimatedTimeMinutes: 60,
    agentSlug: 'marketing_orchestrator',
    sections: [
      { title: 'ICP', description: 'من بالضبط؟' },
      { title: 'Wedge', description: 'أول feature تكسب بها.' },
      { title: 'Channels', description: 'Top 3 channels.' },
      { title: 'Messaging', description: 'Positioning statement.' },
      { title: 'Funnel', description: 'Awareness → revenue.' },
      { title: 'Goals', description: '90-day targets.' },
    ],
    outcomes: ['Canvas Figma', 'Examples', 'Workshop guide'],
    keywords: ['GTM', 'go-to-market', 'canvas'],
  },
  {
    slug: 'meeting-cadence',
    titleAr: 'نظام Meetings للستارت أب',
    titleEn: 'Startup Meeting Cadence',
    metaDescriptionAr: 'نظام meetings كامل: daily standups، weekly reviews، monthly planning.',
    metaDescriptionEn: 'Full meeting system: daily standups, weekly reviews, monthly planning.',
    category: 'operations',
    difficulty: 'beginner',
    format: 'notion',
    estimatedTimeMinutes: 45,
    agentSlug: 'plan_builder',
    sections: [
      { title: 'Daily Standup', description: '15 دقيقة، نفس الوقت.' },
      { title: 'Weekly Team Review', description: 'KPIs، blockers.' },
      { title: 'Monthly Strategy', description: 'OKRs، experiments.' },
      { title: 'Quarterly Planning', description: 'OKRs setting.' },
      { title: 'Annual Offsite', description: 'Vision، culture.' },
    ],
    outcomes: ['Templates لكل meeting', 'Cadence calendar', 'Best practices'],
    keywords: ['meetings', 'cadence', 'rituals'],
  },
  {
    slug: 'employee-handbook',
    titleAr: 'دليل الموظف الكامل',
    titleEn: 'Complete Employee Handbook',
    metaDescriptionAr: 'دليل موظف بمعايير عالمية: ثقافة، policies، benefits، expectations.',
    metaDescriptionEn: 'World-class employee handbook: culture, policies, benefits, expectations.',
    category: 'hr',
    difficulty: 'intermediate',
    format: 'notion',
    estimatedTimeMinutes: 90,
    agentSlug: 'hr_orchestrator',
    sections: [
      { title: 'Welcome & Culture', description: 'Mission، values، vibe.' },
      { title: 'Policies', description: 'Conduct، harassment، confidentiality.' },
      { title: 'Compensation & Benefits', description: 'Salary، bonus، equity، insurance.' },
      { title: 'Time Off', description: 'Vacation، sick، sabbatical.' },
      { title: 'Performance Reviews', description: 'Cadence، criteria.' },
      { title: 'Career Growth', description: 'Levels، promotions.' },
    ],
    outcomes: ['Handbook كامل', 'Compliant مع القانون', 'Onboarding-ready'],
    keywords: ['employee handbook', 'دليل موظف', 'HR policies'],
  },
  {
    slug: 'security-policy',
    titleAr: 'Security Policy للستارت أب',
    titleEn: 'Startup Security Policy',
    metaDescriptionAr: 'Security policies بمعايير SOC 2: access، encryption، incident response.',
    metaDescriptionEn: 'SOC 2-grade security policies: access, encryption, incident response.',
    category: 'legal',
    difficulty: 'advanced',
    format: 'docx',
    estimatedTimeMinutes: 90,
    agentSlug: 'compliance',
    sections: [
      { title: 'Access Control', description: 'RBAC، MFA، SSO.' },
      { title: 'Data Classification', description: 'Public، internal، confidential.' },
      { title: 'Encryption Standards', description: 'At rest و in transit.' },
      { title: 'Incident Response', description: '24h playbook.' },
      { title: 'Vendor Risk', description: 'Third-party assessment.' },
      { title: 'Backup & DR', description: 'RPO/RTO.' },
    ],
    outcomes: ['Policies كاملة', 'Audit-ready', 'SOC 2 prep'],
    keywords: ['security policy', 'SOC 2', 'compliance'],
  },
  {
    slug: 'privacy-policy-pdpl',
    titleAr: 'Privacy Policy متوافقة مع PDPL',
    titleEn: 'PDPL-Compliant Privacy Policy',
    metaDescriptionAr: 'Privacy policy متوافقة مع قانون 151 المصري وGDPR وSaudi PDPL.',
    metaDescriptionEn: 'Privacy policy compliant with Egyptian PDPL, GDPR, and Saudi PDPL.',
    category: 'legal',
    difficulty: 'intermediate',
    format: 'docx',
    estimatedTimeMinutes: 45,
    agentSlug: 'legal_guide',
    sections: [
      { title: 'Data We Collect', description: 'بدقة وشفافية.' },
      { title: 'How We Use It', description: 'Purposes واضحة.' },
      { title: 'Sharing & Transfers', description: 'Third parties، cross-border.' },
      { title: 'User Rights', description: 'Access، rectification، deletion.' },
      { title: 'Retention Periods', description: 'كم وقت نحتفظ بالبيانات.' },
      { title: 'Contact & Complaints', description: 'DPO، authority.' },
    ],
    outcomes: ['Privacy policy جاهزة', 'Multi-jurisdiction', 'Translation عربية'],
    keywords: ['privacy policy', 'PDPL', 'GDPR', 'سياسة خصوصية'],
  },
  {
    slug: 'roadmap-quarterly',
    titleAr: 'Roadmap ربع سنوي',
    titleEn: 'Quarterly Product Roadmap',
    metaDescriptionAr: 'قالب roadmap بصيغة Now/Next/Later مع prioritization framework.',
    metaDescriptionEn: 'Now/Next/Later roadmap template with prioritization framework.',
    category: 'operations',
    difficulty: 'intermediate',
    format: 'notion',
    estimatedTimeMinutes: 45,
    agentSlug: 'plan_builder',
    sections: [
      { title: 'Now (current quarter)', description: 'مُلتزم به.' },
      { title: 'Next (next quarter)', description: 'محتمل، قابل للتغيير.' },
      { title: 'Later', description: 'Future possibilities.' },
      { title: 'RICE Scoring', description: 'Reach، Impact، Confidence، Effort.' },
      { title: 'Stakeholder Communication', description: 'How to share.' },
    ],
    outcomes: ['Roadmap template', 'RICE scoring sheet', 'Communication plan'],
    keywords: ['roadmap', 'product roadmap', 'planning'],
  },
  {
    slug: 'onboarding-30-60-90',
    titleAr: 'خطة Onboarding للموظفين الجدد',
    titleEn: '30-60-90 Onboarding Plan',
    metaDescriptionAr: 'خطة onboarding احترافية تجعل أي موظف جديد productive في 90 يوم.',
    metaDescriptionEn: 'Professional 30-60-90 onboarding plan that makes any new hire productive.',
    category: 'hr',
    difficulty: 'beginner',
    format: 'notion',
    estimatedTimeMinutes: 45,
    agentSlug: 'hr_orchestrator',
    sections: [
      { title: 'Pre-arrival', description: 'Equipment، accounts، welcome.' },
      { title: 'First Week', description: 'Onboarding sessions، intros.' },
      { title: 'Day 30', description: 'Goals، first project.' },
      { title: 'Day 60', description: 'Owning a workstream.' },
      { title: 'Day 90', description: 'Full velocity، review.' },
    ],
    outcomes: ['Plan template', 'Checklists', 'Review templates'],
    keywords: ['onboarding', 'new hire', '30-60-90'],
  },
  {
    slug: 'fundraising-data-room',
    titleAr: 'هيكل Data Room للتمويل',
    titleEn: 'Fundraising Data Room Structure',
    metaDescriptionAr: 'بنية data room كاملة بـ 60+ document منظمة بمعايير VCs.',
    metaDescriptionEn: '60+ document data room structure organized to VC standards.',
    category: 'pitch-deck',
    difficulty: 'advanced',
    format: 'notion',
    estimatedTimeMinutes: 240,
    agentSlug: 'cfo_agent',
    sections: [
      { title: 'Company Overview', description: 'Pitch، team، vision.' },
      { title: 'Product', description: 'Demo، roadmap، tech.' },
      { title: 'Market', description: 'Research، sizing، competition.' },
      { title: 'Financials', description: 'P&L، cash flow، model.' },
      { title: 'Customer & GTM', description: 'Cohorts، CAC، LTV.' },
      { title: 'Team', description: 'Org، hiring، compensation.' },
      { title: 'Legal', description: 'Incorporation، IP، contracts.' },
    ],
    outcomes: ['Folder structure', 'Document checklist', 'NDA templates'],
    keywords: ['data room', 'due diligence', 'fundraising'],
  },
  {
    slug: 'msa-template',
    titleAr: 'Master Service Agreement (MSA)',
    titleEn: 'Master Service Agreement',
    metaDescriptionAr: 'MSA احترافي للـ B2B sales، قابل للتعديل لكل عميل.',
    metaDescriptionEn: 'Professional B2B MSA, customizable per customer.',
    category: 'legal',
    difficulty: 'advanced',
    format: 'docx',
    estimatedTimeMinutes: 60,
    agentSlug: 'legal_guide',
    sections: [
      { title: 'Definitions', description: 'Terms used throughout.' },
      { title: 'Services', description: 'بـ SOWs ملحقة.' },
      { title: 'Payment Terms', description: 'Net 30/60، penalties.' },
      { title: 'IP & Ownership', description: 'Work-for-hire، licenses.' },
      { title: 'Confidentiality', description: 'NDAs، perpetual.' },
      { title: 'Liability & Indemnification', description: 'Caps، carve-outs.' },
      { title: 'Termination', description: 'For convenience، for cause.' },
      { title: 'Dispute Resolution', description: 'Jurisdiction، arbitration.' },
    ],
    outcomes: ['MSA template', 'SOW template', 'Order form template'],
    keywords: ['MSA', 'service agreement', 'B2B contract'],
  },
  {
    slug: 'ad-creative-brief',
    titleAr: 'Creative Brief للإعلانات',
    titleEn: 'Ad Creative Brief',
    metaDescriptionAr: 'Creative brief احترافي لطلب إعلانات من designers أو agencies.',
    metaDescriptionEn: 'Professional creative brief for requesting ads from designers or agencies.',
    category: 'marketing',
    difficulty: 'beginner',
    format: 'notion',
    estimatedTimeMinutes: 20,
    agentSlug: 'marketing_orchestrator',
    sections: [
      { title: 'Background', description: 'Brand، product، context.' },
      { title: 'Objective', description: 'ماذا تريد تحقيق.' },
      { title: 'Audience', description: 'Persona، insights.' },
      { title: 'Key Message', description: 'الرسالة الواحدة الأساسية.' },
      { title: 'Tone & Style', description: 'Brand voice.' },
      { title: 'Deliverables', description: 'Formats، sizes، channels.' },
      { title: 'Budget & Timeline', description: 'واقعي.' },
    ],
    outcomes: ['Brief template', 'Examples', 'Review checklist'],
    keywords: ['creative brief', 'ad brief', 'marketing brief'],
  },
  {
    slug: 'compensation-band',
    titleAr: 'هيكل رواتب احترافي',
    titleEn: 'Compensation Bands Structure',
    metaDescriptionAr: 'هيكل رواتب بـ levels وbands واضحة لتجنب الـ comp arbitrage.',
    metaDescriptionEn: 'Levels-and-bands compensation structure to avoid comp arbitrage.',
    category: 'hr',
    difficulty: 'advanced',
    format: 'xlsx',
    estimatedTimeMinutes: 120,
    agentSlug: 'hr_orchestrator',
    sections: [
      { title: 'Levels Definition', description: 'L1-L7 with criteria.' },
      { title: 'Salary Bands', description: 'Per level، per location.' },
      { title: 'Equity Grants', description: 'Per level.' },
      { title: 'Bonus Structure', description: 'Performance-based.' },
      { title: 'Promotion Criteria', description: 'Clear gates.' },
    ],
    outcomes: ['Comp matrix Excel', 'Promotion playbook', 'Market benchmarks'],
    keywords: ['compensation', 'salary bands', 'equity'],
  },
  {
    slug: 'kpi-dashboard',
    titleAr: 'KPI Dashboard للستارت أب',
    titleEn: 'Startup KPI Dashboard',
    metaDescriptionAr: 'Dashboard أساسي يتتبع كل metrics مهمة لمؤسس أسبوعياً.',
    metaDescriptionEn: 'Essential dashboard tracking every key startup metric weekly.',
    category: 'operations',
    difficulty: 'intermediate',
    format: 'xlsx',
    estimatedTimeMinutes: 60,
    agentSlug: 'cfo_agent',
    sections: [
      { title: 'Acquisition', description: 'Visits، signups، CAC.' },
      { title: 'Activation', description: 'Aha moment rate.' },
      { title: 'Revenue', description: 'MRR، growth، churn.' },
      { title: 'Engagement', description: 'DAU/MAU، retention.' },
      { title: 'Financial', description: 'Burn، runway، margins.' },
    ],
    outcomes: ['Dashboard Excel', 'Weekly review template', 'Alert thresholds'],
    keywords: ['KPI', 'metrics', 'dashboard', 'analytics'],
  },
];

export function getTemplateBySlug(slug: string): SeoTemplate | undefined {
  return TEMPLATES.find((t) => t.slug === slug);
}

export function getAllTemplateSlugs(): string[] {
  return TEMPLATES.map((t) => t.slug);
}

export function getTemplatesByCategory(category: SeoTemplate['category']): SeoTemplate[] {
  return TEMPLATES.filter((t) => t.category === category);
}
