/**
 * Programmatic SEO — Use Cases data layer.
 * Each use case becomes a dedicated landing page targeting Arabic search intent.
 * Pages: /use-cases/[slug]
 */

export interface UseCase {
  slug: string;
  titleAr: string;
  titleEn: string;
  metaDescriptionAr: string;
  metaDescriptionEn: string;
  heroIntroAr: string;
  primaryAgents: string[];
  steps: { title: string; description: string }[];
  outcomes: string[];
  relatedKeywords: string[];
  industry?: string;
  estimatedTimeMinutes: number;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

export const USE_CASES: UseCase[] = [
  {
    slug: 'launch-cloud-restaurant',
    titleAr: 'تأسيس مطعم سحابي في مصر',
    titleEn: 'Launch a Cloud Restaurant in Egypt',
    metaDescriptionAr: 'دليل شامل لتأسيس مطعم سحابي في مصر باستخدام كلميرون: من تقييم الفكرة، التراخيص، التكاليف، إلى أول طلبية.',
    metaDescriptionEn: 'Complete guide to launching a cloud restaurant in Egypt with Kalmeron: from idea validation to first order.',
    heroIntroAr: 'المطاعم السحابية تنمو 32% سنوياً في مصر. كلميرون يجمع 7 وكلاء متخصصين لمساعدتك في كل مرحلة، من اختيار المطبخ المناسب إلى احتساب نقطة التعادل.',
    primaryAgents: ['idea_validator', 'cfo_agent', 'legal_guide', 'marketing_orchestrator', 'opportunity_radar'],
    steps: [
      { title: 'تحقق من الفكرة', description: 'حلّل سوق منطقتك، حدد الفجوة، وقيّم الطلب على نوع الطعام.' },
      { title: 'النموذج المالي', description: 'احسب تكلفة المطبخ، الموظفين، التغليف، التوصيل، وحدد نقطة التعادل.' },
      { title: 'التراخيص القانونية', description: 'سجل تجاري، رخصة تشغيل، ترخيص صحي، وعقود مع منصات التوصيل.' },
      { title: 'استراتيجية الإطلاق', description: 'حملة رقمية مستهدفة، شراكات مع طلبات/Glovo، وعروض إطلاق.' },
      { title: 'التشغيل والتطوير', description: 'مراقبة لحظية للأداء، تحسين القائمة، وتوسع المناطق المخدومة.' },
    ],
    outcomes: [
      'خطة عمل تفصيلية جاهزة للمستثمرين',
      'نموذج مالي 36 شهراً (Excel)',
      'قائمة كاملة بالتراخيص والوثائق المطلوبة',
      'استراتيجية تسويق رقمي مع ميزانية',
      'لوحة قياس KPIs أسبوعية',
    ],
    relatedKeywords: ['مطعم سحابي', 'cloud kitchen مصر', 'تأسيس مطعم', 'دراسة جدوى مطعم'],
    industry: 'food-beverage',
    estimatedTimeMinutes: 90,
    difficulty: 'intermediate',
  },
  {
    slug: 'build-ecommerce-store',
    titleAr: 'بناء متجر إلكتروني ناجح من الصفر',
    titleEn: 'Build a Successful E-commerce Store from Zero',
    metaDescriptionAr: 'خطوات تأسيس متجر إلكتروني في السوق المصري، مع اختيار المنتج، المنصة، الشحن، والدفع.',
    metaDescriptionEn: 'Step-by-step guide to launching an e-commerce store in Egypt, from product to payment.',
    heroIntroAr: 'سوق التجارة الإلكترونية في مصر تجاوز $9 مليار في 2025. كلميرون يساعدك في اختيار المنتج، بناء المتجر، وجلب أول 1000 عميل.',
    primaryAgents: ['idea_validator', 'marketing_orchestrator', 'cfo_agent', 'opportunity_radar'],
    steps: [
      { title: 'اختيار المنتج', description: 'تحليل اتجاهات السوق، اختبار 5 منتجات على شخصيات افتراضية.' },
      { title: 'بناء المتجر', description: 'اختيار المنصة (Shopify/WooCommerce)، تصميم، صور احترافية.' },
      { title: 'حلول الدفع والشحن', description: 'Fawry, InstaPay, Paymob + شراكات Bosta/Aramex.' },
      { title: 'استراتيجية التسويق', description: 'Meta Ads، TikTok، Influencers، حملات Search.' },
      { title: 'تحسين التحويل', description: 'A/B testing، تحسين سلة الدفع، استرداد العربات المتروكة.' },
    ],
    outcomes: ['متجر جاهز للإطلاق', 'استراتيجية تسويق 90 يوم', 'ميزانية إعلانية محسّنة', 'قائمة موردين موثوقين'],
    relatedKeywords: ['متجر إلكتروني مصر', 'تجارة إلكترونية', 'shopify عربي', 'بيع أونلاين'],
    industry: 'ecommerce',
    estimatedTimeMinutes: 120,
    difficulty: 'beginner',
  },
  {
    slug: 'raise-seed-funding',
    titleAr: 'الحصول على تمويل Seed لشركتك الناشئة',
    titleEn: 'Raise Seed Funding for Your Startup',
    metaDescriptionAr: 'كيف تجهز شركتك للحصول على تمويل seed: العرض، النموذج المالي، Term Sheet، والتفاوض مع المستثمرين.',
    metaDescriptionEn: 'How to prepare your startup for seed funding: pitch, financial model, term sheet, investor negotiation.',
    heroIntroAr: 'متوسط جولة seed في مصر $300K-$1M. كلميرون يبني عرضك، نموذجك المالي، ويربطك بـ VCs المناسبين.',
    primaryAgents: ['cfo_agent', 'legal_guide', 'opportunity_radar', 'plan_builder'],
    steps: [
      { title: 'تجهيز Pitch Deck', description: '12 شريحة بمعايير Sequoia، مع تخصيص للسوق المصري.' },
      { title: 'النموذج المالي', description: 'توقعات 36 شهراً، Cohort Analysis، Unit Economics.' },
      { title: 'Investor List', description: 'قائمة مخصصة بـ 50 VC نشطين في قطاعك.' },
      { title: 'Outreach Strategy', description: 'رسائل مخصصة، تتبع، ومتابعة.' },
      { title: 'Term Sheet & Closing', description: 'مراجعة قانونية، تفاوض، إغلاق الصفقة.' },
    ],
    outcomes: ['Pitch deck بمعايير عالمية', 'نموذج مالي قابل للدفاع', '50 لقاء مستثمر', 'مساعدة قانونية في Term Sheet'],
    relatedKeywords: ['seed funding مصر', 'تمويل ناشئ', 'pitch deck', 'مستثمرين'],
    industry: 'fintech',
    estimatedTimeMinutes: 180,
    difficulty: 'advanced',
  },
  {
    slug: 'validate-saas-idea',
    titleAr: 'تحقق من فكرة SaaS قبل البناء',
    titleEn: 'Validate Your SaaS Idea Before Building',
    metaDescriptionAr: 'لا تبني منتج لا أحد يريده. كلميرون يختبر فكرتك على 200 شخصية تركيبية ويعطيك تقرير قابلية تسويق.',
    metaDescriptionEn: "Don't build what nobody wants. Kalmeron tests your idea against 200 synthetic personas.",
    heroIntroAr: 'دراسة CB Insights: 42% من الستارت أبس تفشل بسبب "no market need". كلميرون يحميك من هذا الخطر.',
    primaryAgents: ['idea_validator', 'mistake_shield', 'success_museum', 'opportunity_radar'],
    steps: [
      { title: 'وصف الفكرة', description: 'بالعامية أو الفصحى. كلميرون يستخرج المتغيرات المهمة.' },
      { title: 'تحليل السوق', description: 'حجم، نمو، منافسين، فجوات.' },
      { title: 'اختبار الشخصيات', description: 'اختبار pitch على 200 شخصية مصرية تركيبية.' },
      { title: 'تقرير المخاطر', description: 'Top 10 risks مع mitigation لكل منها.' },
      { title: 'الخطوة التالية', description: 'go / pivot / no-go مع مبررات قابلة للدفاع.' },
    ],
    outcomes: ['تقرير تحقق 30 صفحة', 'قياس Product-Market Fit Probability', 'قائمة بـ 5 pivots محتملة'],
    relatedKeywords: ['تحقق من فكرة', 'product market fit', 'SaaS validation', 'دراسة جدوى'],
    industry: 'saas',
    estimatedTimeMinutes: 60,
    difficulty: 'beginner',
  },
  {
    slug: 'launch-fintech-app',
    titleAr: 'إطلاق تطبيق فنتك في السوق المصري',
    titleEn: 'Launch a Fintech App in Egypt',
    metaDescriptionAr: 'دليل تأسيس تطبيق فنتك في مصر: تراخيص البنك المركزي، الامتثال، التكامل مع Fawry/InstaPay، والنمو.',
    metaDescriptionEn: 'Guide to launching a fintech in Egypt: CBE licensing, compliance, payment integration, and growth.',
    heroIntroAr: 'القطاع المالي في مصر يجذب 40% من تمويل الستارت أبس. كلميرون يرشدك في الـ regulation المعقد.',
    primaryAgents: ['legal_guide', 'cfo_agent', 'compliance', 'idea_validator'],
    steps: [
      { title: 'فهم Regulation', description: 'BNPL, e-wallet, payment aggregator — أي ترخيص تحتاج؟' },
      { title: 'تجهيز الوثائق للبنك المركزي', description: 'KYC, AML, Risk Management policies.' },
      { title: 'بنية التطبيق التقنية', description: 'PCI-DSS, encryption, fraud detection.' },
      { title: 'التكامل مع البنية التحتية', description: 'Fawry, InstaPay, Meeza, Banking APIs.' },
      { title: 'استراتيجية النمو', description: 'Acquisition channels, retention, viral loops.' },
    ],
    outcomes: ['Compliance roadmap كامل', 'وثائق جاهزة للبنك المركزي', 'بنية تقنية موصى بها'],
    relatedKeywords: ['fintech مصر', 'البنك المركزي', 'محفظة إلكترونية', 'تطبيق دفع'],
    industry: 'fintech',
    estimatedTimeMinutes: 240,
    difficulty: 'advanced',
  },
  {
    slug: 'build-mvp-30-days',
    titleAr: 'بناء MVP في 30 يوم بميزانية محدودة',
    titleEn: 'Build an MVP in 30 Days on a Tight Budget',
    metaDescriptionAr: 'منهجية مدروسة لبناء أول نسخة من منتجك في 30 يوم بأقل من $5000.',
    metaDescriptionEn: 'Methodology to build your first product version in 30 days under $5K.',
    heroIntroAr: 'لا تحتاج $50K لتبدأ. كلميرون يخطط لك Sprint مدته 30 يوم لإطلاق MVP حقيقي.',
    primaryAgents: ['plan_builder', 'idea_validator', 'mistake_shield'],
    steps: [
      { title: 'Scope Definition', description: 'فقط 3 features. لا غير.' },
      { title: 'Tech Stack الذكي', description: 'No-code / low-code أولاً، code فقط لو ضروري.' },
      { title: 'Week-by-Week Plan', description: 'كل أسبوع له milestone قابل للقياس.' },
      { title: 'Testing مع المستخدمين', description: 'الأسبوع 3-4 = جلسات user testing.' },
      { title: 'Iteration وLaunch', description: 'إصلاح أهم 5 issues + soft launch.' },
    ],
    outcomes: ['MVP يعمل في 30 يوم', 'أول 50 user تجريبي', 'Roadmap للـ V2'],
    relatedKeywords: ['MVP', 'بناء منتج', 'no-code', 'إطلاق ستارت أب'],
    industry: 'saas',
    estimatedTimeMinutes: 60,
    difficulty: 'intermediate',
  },
  {
    slug: 'pricing-strategy',
    titleAr: 'استراتيجية التسعير الذكي لمنتجك',
    titleEn: 'Smart Pricing Strategy for Your Product',
    metaDescriptionAr: 'لا تخمّن سعرك. كلميرون يبني نموذج Value-Based Pricing مدعوم بأبحاث المنافسين.',
    metaDescriptionEn: 'Stop guessing prices. Kalmeron builds a value-based pricing model backed by competitor research.',
    heroIntroAr: 'دراسة McKinsey: تحسين التسعير 1% يرفع الأرباح 8%. كلميرون يجد لك السعر المثالي.',
    primaryAgents: ['cfo_agent', 'idea_validator', 'success_museum'],
    steps: [
      { title: 'تحليل المنافسين', description: 'كل منافس، كل خطة، كل ميزة، بالتفصيل.' },
      { title: 'Willingness-to-Pay Survey', description: 'اختبار 5 نقاط سعرية على personas.' },
      { title: 'نموذج Tiered Pricing', description: 'Anchor + Target + Decoy strategy.' },
      { title: 'Annual vs Monthly', description: 'كم خصم؟ كم cash flow ستحصل؟' },
      { title: 'A/B Test على الموقع', description: 'مع تتبع conversion ومعدل الـ churn.' },
    ],
    outcomes: ['نموذج تسعير مدروس', '3-4 خطط محسّنة', 'حسابات LTV:CAC'],
    relatedKeywords: ['تسعير', 'pricing strategy', 'SaaS pricing', 'subscription'],
    estimatedTimeMinutes: 75,
    difficulty: 'intermediate',
  },
  {
    slug: 'hire-first-team',
    titleAr: 'بناء أول فريق لشركتك الناشئة',
    titleEn: "Build Your Startup's First Team",
    metaDescriptionAr: 'متى توظف؟ من توظف أولاً؟ كم تدفع؟ كلميرون يبني خطة hire-by-hire لأول 10 موظفين.',
    metaDescriptionEn: 'When to hire? Who first? How much? Kalmeron builds a hire-by-hire plan for your first 10 employees.',
    heroIntroAr: 'أكبر خطأ في الستارت أبس: التوظيف المتأخر أو المبكر. كلميرون يحدد التوقيت المثالي.',
    primaryAgents: ['hr_orchestrator', 'cfo_agent', 'legal_guide'],
    steps: [
      { title: 'تحديد الأدوار الأهم', description: 'بناءً على stage و stack.' },
      { title: 'Job Descriptions', description: 'JD احترافي يجذب أفضل المواهب.' },
      { title: 'Compensation Benchmarking', description: 'كم يدفع المنافسون في مصر؟' },
      { title: 'عقود وامتثال', description: 'عقد عمل، sec ration, equity vesting.' },
      { title: 'Onboarding Plan', description: 'أول 30/60/90 يوم لكل موظف.' },
    ],
    outcomes: ['Hiring plan لـ 12 شهر', '10 JDs جاهزة', 'عقود قانونية مصرية'],
    relatedKeywords: ['توظيف', 'hiring startup', 'موارد بشرية', 'عقد عمل'],
    estimatedTimeMinutes: 90,
    difficulty: 'intermediate',
  },
  {
    slug: 'expand-to-saudi-uae',
    titleAr: 'التوسع للسوق السعودي والإماراتي',
    titleEn: 'Expand to Saudi Arabia and UAE Markets',
    metaDescriptionAr: 'دليل التوسع من مصر إلى الخليج: التراخيص، الشركاء، التسويق المحلي، والتسعير المختلف.',
    metaDescriptionEn: 'Guide to expanding from Egypt to the Gulf: licensing, partners, localization, and pricing.',
    heroIntroAr: 'السوق الخليجي 4× القوة الشرائية للمصري. كلميرون يخطط لك التوسع بدون أخطاء مكلفة.',
    primaryAgents: ['legal_guide', 'cfo_agent', 'marketing_orchestrator', 'opportunity_radar'],
    steps: [
      { title: 'اختر السوق المناسب', description: 'KSA vs UAE vs both — تحليل تفصيلي.' },
      { title: 'هيكل قانوني', description: 'فرع، LLC، توكيل، أم شراكة محلية.' },
      { title: 'تسعير ودفع محلي', description: 'SAR/AED، ضريبة VAT، وسائل دفع محلية.' },
      { title: 'تسويق محلي', description: 'لهجة، قيم ثقافية، قنوات الـ MENA.' },
      { title: 'Talent + Operations', description: 'فريق محلي vs ريموت من القاهرة.' },
    ],
    outcomes: ['خطة توسع مفصلة', 'تكلفة تأسيس متوقعة', 'قائمة شركاء محتملين'],
    relatedKeywords: ['التوسع للسعودية', 'دبي', 'سوق الخليج', 'GCC expansion'],
    estimatedTimeMinutes: 150,
    difficulty: 'advanced',
  },
  {
    slug: 'build-content-marketing',
    titleAr: 'بناء محرك تسويق محتوى للستارت أب',
    titleEn: 'Build a Content Marketing Engine for Your Startup',
    metaDescriptionAr: 'استراتيجية محتوى تجلب 10K زائر شهرياً في 6 أشهر، بدون ميزانية إعلانية كبيرة.',
    metaDescriptionEn: 'Content strategy bringing 10K monthly visitors in 6 months without big ad budget.',
    heroIntroAr: 'SEO يبني أصلاً. كل مقالة هي employee يعمل 24/7 بدون أجر. كلميرون يبني لك المحرك.',
    primaryAgents: ['marketing_orchestrator', 'seo_manager', 'content_creator'],
    steps: [
      { title: 'بحث الكلمات المفتاحية', description: '50 keyword عربي قابل للترتيب.' },
      { title: 'Content Calendar 90 يوم', description: '3 مقالات/أسبوع موزعة استراتيجياً.' },
      { title: 'بناء أول 30 مقالة', description: 'بمساعدة كلميرون، جودة عالية.' },
      { title: 'Distribution Strategy', description: 'Email, social, partnerships.' },
      { title: 'Measurement', description: 'GA4, Search Console, conversion tracking.' },
    ],
    outcomes: ['30 مقالة عالية الجودة', '50 keyword مرتب', '10K زائر شهري متوقع'],
    relatedKeywords: ['تسويق محتوى', 'SEO عربي', 'blog strategy', 'inbound marketing'],
    estimatedTimeMinutes: 120,
    difficulty: 'intermediate',
  },
  {
    slug: 'launch-d2c-fashion-brand',
    titleAr: 'إطلاق علامة أزياء D2C في السوق العربي',
    titleEn: 'Launch a D2C Fashion Brand in MENA',
    metaDescriptionAr: 'دليل بناء علامة أزياء مباشرة للمستهلك من اختيار المنتج، التصنيع، التسويق، إلى التحجيم.',
    metaDescriptionEn: 'Build a Direct-to-Consumer fashion brand in MENA: from sourcing to scale.',
    heroIntroAr: 'سوق الأزياء العربي $54 مليار. كلميرون يساعدك تبني علامة D2C تنافس الكبار.',
    primaryAgents: ['idea_validator', 'marketing_orchestrator', 'cfo_agent'],
    steps: [
      { title: 'تحديد الهوية والـ Niche', description: 'modest fashion، streetwear، luxury، أو sustainable.' },
      { title: 'Sourcing وTصنيع', description: 'ورش 10th of Ramadan، Türkiye، أو China.' },
      { title: 'الـ Brand Identity', description: 'Logo، packaging، tone of voice، content style.' },
      { title: 'Launch Strategy', description: 'Drop model، Instagram، influencers، PR.' },
      { title: 'Operations والـ Returns', description: 'Bosta، COD %، returns policy، loyalty program.' },
    ],
    outcomes: ['خطة منتج كاملة', 'موردين موثوقين', 'استراتيجية launch 90 يوم', 'Unit economics صحيح'],
    relatedKeywords: ['fashion brand', 'D2C', 'علامة أزياء', 'modest fashion'],
    industry: 'ecommerce',
    estimatedTimeMinutes: 150,
    difficulty: 'intermediate',
  },
  {
    slug: 'series-a-fundraising',
    titleAr: 'الحصول على تمويل Series A',
    titleEn: 'Raise Series A Funding',
    metaDescriptionAr: 'كيف تنتقل من Seed إلى Series A: KPIs، Pitch، Term Sheet، والتفاوض مع VCs الإقليميين والعالميين.',
    metaDescriptionEn: 'How to move from Seed to Series A: metrics, pitch, term sheet, regional and global VCs.',
    heroIntroAr: 'متوسط Series A في MENA $5-15M. كلميرون يساعدك تجهز شركتك وتختار المستثمرين الصح.',
    primaryAgents: ['cfo_agent', 'plan_builder', 'legal_guide', 'opportunity_radar'],
    steps: [
      { title: 'تجهيز الـ Metrics', description: 'ARR ≥ $1M، growth ≥ 15% MoM، NRR ≥ 110%.' },
      { title: 'بناء Data Room', description: '60+ document منظمة باحتراف.' },
      { title: 'Pitch Deck لـ Series A', description: '15 شريحة مع market sizing عميق.' },
      { title: 'استهداف الـ VCs', description: '40 VC مناسبين (regional + global).' },
      { title: 'Negotiation وClosing', description: 'Term sheet، 409A، lawyers، wire.' },
    ],
    outcomes: ['Data room كامل', 'Investor list 40+ VCs', 'Term sheet مفاوض', 'Closing in 4-6 شهور'],
    relatedKeywords: ['Series A', 'تمويل سيريز إيه', 'VC funding', 'venture capital MENA'],
    industry: 'fintech',
    estimatedTimeMinutes: 240,
    difficulty: 'advanced',
  },
  {
    slug: 'launch-b2b-saas',
    titleAr: 'إطلاق منصة B2B SaaS للسوق العربي',
    titleEn: 'Launch a B2B SaaS Platform in MENA',
    metaDescriptionAr: 'بناء منصة B2B SaaS من الفكرة لأول 100 عميل، مع GTM لسوق المؤسسات العربية.',
    metaDescriptionEn: 'Build a B2B SaaS from idea to first 100 customers, GTM for Arab enterprises.',
    heroIntroAr: 'B2B SaaS في MENA يضاعف نفسه كل سنتين. كلميرون يبنيلك GTM strategy تناسب الثقافة المحلية.',
    primaryAgents: ['idea_validator', 'plan_builder', 'marketing_orchestrator', 'cfo_agent'],
    steps: [
      { title: 'ICP Definition', description: 'Industry + size + role + pain.' },
      { title: 'Outbound Sales Setup', description: 'CRM + sequencing + SDR playbook.' },
      { title: 'Pricing & Packaging', description: 'Per seat / usage / tiered.' },
      { title: 'Customer Success', description: 'Onboarding، QBRs، expansion playbook.' },
      { title: 'Land & Expand', description: 'دخول صغير، expansion سريع.' },
    ],
    outcomes: ['Sales playbook كامل', 'CRM setup', 'Pricing pages', 'أول 10 عقود'],
    relatedKeywords: ['B2B SaaS', 'enterprise sales', 'بيع للمؤسسات'],
    industry: 'saas',
    estimatedTimeMinutes: 180,
    difficulty: 'advanced',
  },
  {
    slug: 'launch-edtech-platform',
    titleAr: 'إطلاق منصة تعليم إلكتروني',
    titleEn: 'Launch an EdTech Platform',
    metaDescriptionAr: 'بناء منصة EdTech في السوق العربي: Content، Pedagogy، Tech، وGo-to-market.',
    metaDescriptionEn: 'Build an EdTech platform in MENA: content, pedagogy, tech, and GTM.',
    heroIntroAr: 'سوق EdTech العربي $7B وفي نمو. كلميرون يفهم احتياجات الطلاب والمعلمين والأهل.',
    primaryAgents: ['idea_validator', 'marketing_orchestrator', 'plan_builder'],
    steps: [
      { title: 'تحديد الفئة المستهدفة', description: 'K-12، university، professional، أو vocational.' },
      { title: 'Content Strategy', description: 'Curriculum، instructors، formats.' },
      { title: 'Technology Stack', description: 'LMS، video، mobile، assessment engine.' },
      { title: 'B2C vs B2B vs B2G', description: 'بيع للأفراد، المدارس، أو الحكومة.' },
      { title: 'الـ Acquisition Engine', description: 'Parent groups، WhatsApp، influencers.' },
    ],
    outcomes: ['MVP منصة', '50 درس مسجل', 'استراتيجية النمو', 'أول 1000 طالب'],
    relatedKeywords: ['edtech', 'تعليم إلكتروني', 'منصة تعليمية', 'online learning'],
    industry: 'edtech',
    estimatedTimeMinutes: 150,
    difficulty: 'intermediate',
  },
  {
    slug: 'launch-healthtech-app',
    titleAr: 'إطلاق تطبيق صحي رقمي',
    titleEn: 'Launch a Digital Health App',
    metaDescriptionAr: 'بناء تطبيق Healthtech: telemedicine، booking، أو wellness. مع الامتثال لقوانين الصحة.',
    metaDescriptionEn: 'Build a healthtech app: telemedicine, booking, or wellness with health compliance.',
    heroIntroAr: 'الصحة الرقمية في مصر تنمو 40% سنوياً. كلميرون يرشدك في الامتثال والـ trust building.',
    primaryAgents: ['idea_validator', 'legal_guide', 'compliance', 'marketing_orchestrator'],
    steps: [
      { title: 'تحديد النموذج', description: 'Telemedicine، booking، EHR، أو insurance.' },
      { title: 'الامتثال الصحي', description: 'وزارة الصحة، نقابة الأطباء، privacy.' },
      { title: 'بناء شبكة الأطباء', description: 'Onboarding، credentialing، quality control.' },
      { title: 'Patient Acquisition', description: 'GP referrals، clinics، insurance partners.' },
      { title: 'Trust Building', description: 'Reviews، testimonials، doctor profiles.' },
    ],
    outcomes: ['تطبيق MVP', '100 طبيب موقّع', 'استراتيجية امتثال', 'أول 5000 مستخدم'],
    relatedKeywords: ['healthtech', 'صحة رقمية', 'telemedicine', 'تطبيق طبي'],
    industry: 'healthtech',
    estimatedTimeMinutes: 200,
    difficulty: 'advanced',
  },
  {
    slug: 'go-to-market-strategy',
    titleAr: 'بناء استراتيجية Go-to-Market متكاملة',
    titleEn: 'Build a Complete Go-to-Market Strategy',
    metaDescriptionAr: 'GTM Strategy احترافية: positioning، messaging، channels، sales motion، وكل ما يحتاجه إطلاق ناجح.',
    metaDescriptionEn: 'Professional GTM: positioning, messaging, channels, sales motion for a successful launch.',
    heroIntroAr: 'منتج ممتاز بدون GTM = فشل مضمون. كلميرون يبني معك خطة launch احترافية بمعايير Silicon Valley.',
    primaryAgents: ['marketing_orchestrator', 'idea_validator', 'plan_builder'],
    steps: [
      { title: 'Positioning Framework', description: 'Category، competitive frame، differentiation.' },
      { title: 'ICP & Personas', description: '3 personas تفصيلية مع pain points.' },
      { title: 'Messaging House', description: 'Tagline، value props، proof points.' },
      { title: 'Channel Mix', description: 'Paid، organic، PLG، sales-led، channel partners.' },
      { title: 'Launch Calendar', description: 'Pre-launch، launch day، post-launch 30/60/90.' },
    ],
    outcomes: ['GTM doc مكتمل', 'Messaging guide', 'Launch plan 90 يوم', 'KPIs مفصّلة'],
    relatedKeywords: ['go-to-market', 'GTM strategy', 'launch plan', 'positioning'],
    estimatedTimeMinutes: 180,
    difficulty: 'advanced',
  },
  {
    slug: 'reduce-customer-churn',
    titleAr: 'تقليل معدل الـ Churn في منتجك',
    titleEn: 'Reduce Customer Churn in Your Product',
    metaDescriptionAr: 'استراتيجيات إثبتت فعاليتها لتقليل churn 50%+ في SaaS وsubscription products.',
    metaDescriptionEn: 'Proven strategies to reduce churn 50%+ in SaaS and subscription products.',
    heroIntroAr: 'تقليل churn 5% يضاعف الـ LTV. كلميرون يحلل بياناتك ويبنيلك خطة retention.',
    primaryAgents: ['cfo_agent', 'marketing_orchestrator', 'plan_builder'],
    steps: [
      { title: 'Churn Cohort Analysis', description: 'فهم متى ولماذا يخرج العملاء.' },
      { title: 'Voice of Customer', description: 'Exit interviews + NPS surveys.' },
      { title: 'Onboarding Redesign', description: '80% من churn يحدث في أول 30 يوم.' },
      { title: 'Customer Success Motion', description: 'Health scores، QBRs، playbooks.' },
      { title: 'Win-back Campaigns', description: 'استرجاع 15-25% من الـ churned.' },
    ],
    outcomes: ['Churn report', 'Retention plan', 'Onboarding redesign', 'Win-back automation'],
    relatedKeywords: ['churn', 'retention', 'customer success', 'CSAT'],
    industry: 'saas',
    estimatedTimeMinutes: 120,
    difficulty: 'intermediate',
  },
  {
    slug: 'build-marketplace',
    titleAr: 'بناء Marketplace ثنائي الجوانب',
    titleEn: 'Build a Two-Sided Marketplace',
    metaDescriptionAr: 'كيف تبني marketplace ناجح: حل chicken-and-egg، supply seeding، unit economics.',
    metaDescriptionEn: 'How to build a successful marketplace: solve chicken-and-egg, supply seeding, unit economics.',
    heroIntroAr: 'Marketplaces لها network effects أقوى من أي business model. كلميرون يساعدك تبني واحد.',
    primaryAgents: ['idea_validator', 'plan_builder', 'cfo_agent', 'marketing_orchestrator'],
    steps: [
      { title: 'Niche Selection', description: 'Vertical محدد > horizontal عام.' },
      { title: 'Supply Side First', description: 'استراتيجية seeding للموردين.' },
      { title: 'Trust & Safety', description: 'Reviews، escrow، dispute resolution.' },
      { title: 'Take Rate Strategy', description: '5-30% حسب الـ value-add.' },
      { title: 'Liquidity Metrics', description: 'Match rate، time-to-match، GMV.' },
    ],
    outcomes: ['Marketplace MVP', 'Supply seeded', 'Liquidity في niche واحد', 'Unit economics صحي'],
    relatedKeywords: ['marketplace', 'سوق إلكتروني', 'two-sided', 'platform'],
    industry: 'ecommerce',
    estimatedTimeMinutes: 200,
    difficulty: 'advanced',
  },
  {
    slug: 'launch-mobile-app',
    titleAr: 'إطلاق تطبيق موبايل ناجح',
    titleEn: 'Launch a Successful Mobile App',
    metaDescriptionAr: 'من الفكرة إلى App Store Featured: design، development، launch، ومنع الـ uninstall.',
    metaDescriptionEn: 'From idea to App Store Featured: design, development, launch, and prevent uninstalls.',
    heroIntroAr: '1.6M تطبيق في App Store. كلميرون يبنيلك خطة تظهر فيها وسط الزحام.',
    primaryAgents: ['idea_validator', 'plan_builder', 'marketing_orchestrator'],
    steps: [
      { title: 'Native vs Cross-platform', description: 'Flutter، React Native، أو native.' },
      { title: 'ASO Strategy', description: 'Keywords، screenshots، title.' },
      { title: 'Pre-launch Hype', description: 'Landing page، waitlist، beta testers.' },
      { title: 'Launch Day Execution', description: 'PR، influencers، paid push.' },
      { title: 'Retention Loops', description: 'Notifications ذكية، gamification، social.' },
    ],
    outcomes: ['تطبيق منشور', 'ASO محسّن', 'أول 10K تحميل', 'D7 retention > 40%'],
    relatedKeywords: ['mobile app', 'تطبيق موبايل', 'iOS', 'Android'],
    estimatedTimeMinutes: 180,
    difficulty: 'intermediate',
  },
  {
    slug: 'open-physical-store',
    titleAr: 'افتتاح متجر فعلي بدراسة جدوى صحيحة',
    titleEn: 'Open a Physical Store with Proper Feasibility',
    metaDescriptionAr: 'دليل افتتاح متجر فعلي في مصر: الموقع، الديكور، التراخيص، التسعير، والتسويق.',
    metaDescriptionEn: 'Open a physical store in Egypt: location, design, licensing, pricing, marketing.',
    heroIntroAr: 'الـ retail الفيزيائي عاد بقوة. كلميرون يساعدك تختار الموقع الصح وتبني تجربة لا تُنسى.',
    primaryAgents: ['idea_validator', 'cfo_agent', 'legal_guide', 'marketing_orchestrator'],
    steps: [
      { title: 'تحليل الموقع', description: 'Foot traffic، demographics، competition.' },
      { title: 'النموذج المالي', description: 'إيجار، ديكور، موظفين، نقطة التعادل.' },
      { title: 'التراخيص', description: 'سجل تجاري، رخصة محل، حماية مدنية.' },
      { title: 'الـ Store Design', description: 'Layout، lighting، music، sensory branding.' },
      { title: 'Local Marketing', description: 'Soft launch، referrals، loyalty.' },
    ],
    outcomes: ['دراسة جدوى', 'خطة افتتاح', 'تراخيص مكتملة', 'Local marketing plan'],
    relatedKeywords: ['متجر فعلي', 'retail', 'افتتاح محل', 'physical store'],
    industry: 'retail',
    estimatedTimeMinutes: 180,
    difficulty: 'intermediate',
  },
  {
    slug: 'build-personal-brand',
    titleAr: 'بناء علامة شخصية لرائد الأعمال',
    titleEn: 'Build a Personal Brand as a Founder',
    metaDescriptionAr: 'كيف تبني personal brand قوية على LinkedIn وX تجلب لك عملاء، استثمارات، وصفقات.',
    metaDescriptionEn: 'Build a strong personal brand on LinkedIn and X that attracts deals, investors, customers.',
    heroIntroAr: 'Personal brand رواد الأعمال أقوى أصل في القرن 21. كلميرون يبنيلك content engine.',
    primaryAgents: ['marketing_orchestrator', 'plan_builder'],
    steps: [
      { title: 'تحديد الـ Niche', description: 'موضوع واحد محوري + 3 مواضيع داعمة.' },
      { title: 'Content Pillars', description: '5 أنواع منشورات تتكرر.' },
      { title: 'Distribution Calendar', description: 'LinkedIn يومياً، X 3-5 يومياً.' },
      { title: 'Engagement Strategy', description: '15 minutes daily للرد والتفاعل.' },
      { title: 'Conversion Loop', description: 'Newsletter، DMs، calls، deals.' },
    ],
    outcomes: ['Brand strategy', '90-day content calendar', 'Templates للمنشورات', 'KPIs للنمو'],
    relatedKeywords: ['personal brand', 'علامة شخصية', 'LinkedIn', 'thought leadership'],
    estimatedTimeMinutes: 90,
    difficulty: 'beginner',
  },
  {
    slug: 'analyze-competitors',
    titleAr: 'تحليل المنافسين بعمق احترافي',
    titleEn: 'Deep Competitive Analysis',
    metaDescriptionAr: 'منهجية تحليل المنافسين كما تفعلها McKinsey: positioning، pricing، gaps، threats.',
    metaDescriptionEn: 'Competitive analysis methodology like McKinsey: positioning, pricing, gaps, threats.',
    heroIntroAr: 'لا تطلق منتج بدون فهم منافسيك حرفياً كل تفصيلة. كلميرون يجمع ويحلل.',
    primaryAgents: ['idea_validator', 'opportunity_radar', 'marketing_orchestrator'],
    steps: [
      { title: 'تحديد المنافسين', description: 'Direct، indirect، substitute.' },
      { title: 'Feature Matrix', description: '50+ feature مقارنة.' },
      { title: 'Pricing Teardown', description: 'كل خطة، كل tier، كل add-on.' },
      { title: 'Marketing Audit', description: 'SEO، paid، social، PR.' },
      { title: 'Gaps & Opportunities', description: 'أين تفوز، أين تخسر، أين تتفادى.' },
    ],
    outcomes: ['Competitive landscape map', 'Feature/Price matrix', 'Strategic recommendations'],
    relatedKeywords: ['competitive analysis', 'تحليل منافسين', 'market research'],
    estimatedTimeMinutes: 120,
    difficulty: 'intermediate',
  },
  {
    slug: 'tax-planning-startup',
    titleAr: 'تخطيط ضريبي ذكي للستارت أب',
    titleEn: 'Smart Tax Planning for Startups',
    metaDescriptionAr: 'كيف توفر 30%+ من ضرائبك بشكل قانوني: حوافز، خصومات، structuring، وتوقيت ذكي.',
    metaDescriptionEn: 'Save 30%+ on taxes legally: incentives, deductions, structuring, and timing.',
    heroIntroAr: 'الضرائب أكبر مصاريف بعد الرواتب. كلميرون يخطط معك ضرائبياً بعقل CPA.',
    primaryAgents: ['cfo_agent', 'legal_guide', 'compliance'],
    steps: [
      { title: 'فحص الوضع الحالي', description: 'P&L، DTA/DTL، ضرائب مدفوعة.' },
      { title: 'حوافز الستارت أبس', description: 'قانون 159، الإعفاءات، الـ R&D credits.' },
      { title: 'Structuring الذكي', description: 'مصري vs IFZA Free Zone vs Delaware.' },
      { title: 'Timing الإيرادات', description: 'تأجيل، تسريع، deferral.' },
      { title: 'Monthly Tax Review', description: 'مراجعة شهرية مع وكيل CFO.' },
    ],
    outcomes: ['Tax strategy doc', 'Structure recommendation', 'Monthly compliance schedule'],
    relatedKeywords: ['ضرائب', 'tax planning', 'incentives', 'structure'],
    estimatedTimeMinutes: 120,
    difficulty: 'advanced',
  },
  {
    slug: 'build-ai-product',
    titleAr: 'بناء منتج AI من الفكرة للإطلاق',
    titleEn: 'Build an AI Product from Idea to Launch',
    metaDescriptionAr: 'كل ما تحتاجه لبناء منتج AI: model selection، RAG، evaluation، production، والـ moat.',
    metaDescriptionEn: 'Everything to build an AI product: model selection, RAG, evaluation, production, and moat.',
    heroIntroAr: 'AI startup wave فرصة جيلية. كلميرون يساعدك تبني المنتج الصح بدون إعادة اختراع العجلة.',
    primaryAgents: ['idea_validator', 'plan_builder', 'marketing_orchestrator'],
    steps: [
      { title: 'Use Case Validation', description: 'AI ضروري أم zsh؟ ROI واضح؟' },
      { title: 'Model & Architecture', description: 'OpenAI، Anthropic، open-source، fine-tune.' },
      { title: 'RAG وMemory', description: 'Vector DB، chunking، retrieval strategy.' },
      { title: 'Evaluation Suite', description: 'Eval datasets، metrics، LLM-as-judge.' },
      { title: 'Production والـ Cost Control', description: 'Caching، routing، monitoring.' },
    ],
    outcomes: ['AI architecture doc', 'Eval framework', 'Cost projections', 'Production checklist'],
    relatedKeywords: ['AI product', 'منتج AI', 'LLM', 'RAG'],
    industry: 'saas',
    estimatedTimeMinutes: 240,
    difficulty: 'advanced',
  },
  {
    slug: 'manage-cash-flow',
    titleAr: 'إدارة الـ Cash Flow في الستارت أب',
    titleEn: 'Manage Startup Cash Flow',
    metaDescriptionAr: '70% من الستارت أبس تموت بسبب نفاد الكاش. كلميرون يساعدك تتجنب هذا الفخ.',
    metaDescriptionEn: '70% of startups die from running out of cash. Avoid this trap with smart management.',
    heroIntroAr: 'Cash is king. كلميرون يبنيلك dashboard cash flow أسبوعي وتنبيهات قبل الأزمات.',
    primaryAgents: ['cfo_agent', 'plan_builder'],
    steps: [
      { title: '13-Week Cash Flow Forecast', description: 'الأداة الذهبية للـ CFOs.' },
      { title: 'AR Acceleration', description: 'تقليل DSO من 60 إلى 30 يوم.' },
      { title: 'AP Optimization', description: 'تمديد payment terms للموردين.' },
      { title: 'Burn Rate Discipline', description: 'فحص أسبوعي، triggers للـ cuts.' },
      { title: 'Runway Extension', description: 'كيف توفر 6 شهور إضافية بسرعة.' },
    ],
    outcomes: ['Cash flow forecast model', 'AR/AP playbooks', 'Burn rate dashboard'],
    relatedKeywords: ['cash flow', 'تدفق نقدي', 'runway', 'burn rate'],
    estimatedTimeMinutes: 90,
    difficulty: 'intermediate',
  },
  {
    slug: 'build-sales-team',
    titleAr: 'بناء فريق مبيعات احترافي من الصفر',
    titleEn: 'Build a Professional Sales Team from Zero',
    metaDescriptionAr: 'من أول SDR إلى team من 20: hiring، onboarding، compensation، playbooks.',
    metaDescriptionEn: 'From first SDR to team of 20: hiring, onboarding, compensation, playbooks.',
    heroIntroAr: 'مبيعات احترافية = نمو متنبأ به. كلميرون يبنيلك sales org كاملة.',
    primaryAgents: ['hr_orchestrator', 'cfo_agent', 'plan_builder'],
    steps: [
      { title: 'Sales Org Design', description: 'SDR، AE، CSM، RevOps.' },
      { title: 'Compensation Plans', description: 'Base + commission + accelerators.' },
      { title: 'Hiring Pipeline', description: 'Sources، screening، interview loops.' },
      { title: 'Sales Playbook', description: 'Discovery، demo، negotiation، close.' },
      { title: 'Sales Tech Stack', description: 'CRM، sequencing، intelligence، forecasting.' },
    ],
    outcomes: ['Org chart 12 شهر', 'Comp plans', 'Hiring scorecards', 'Sales playbook'],
    relatedKeywords: ['sales team', 'فريق مبيعات', 'enterprise sales', 'SDR'],
    estimatedTimeMinutes: 180,
    difficulty: 'advanced',
  },
  {
    slug: 'protect-intellectual-property',
    titleAr: 'حماية الملكية الفكرية لشركتك',
    titleEn: 'Protect Your Startup IP',
    metaDescriptionAr: 'العلامات التجارية، براءات الاختراع، حقوق النشر، أسرار تجارية: ما تحتاجه ومتى.',
    metaDescriptionEn: 'Trademarks, patents, copyrights, trade secrets: what you need and when.',
    heroIntroAr: 'IP أصل قابل للتقدير. كلميرون يبنيلك خطة حماية شاملة بدون مبالغة في التكلفة.',
    primaryAgents: ['legal_guide', 'compliance'],
    steps: [
      { title: 'IP Audit', description: 'كل ما تملكه - مسجل أم لا.' },
      { title: 'Trademark Strategy', description: 'علامة تجارية في كل سوق مستهدف.' },
      { title: 'Patents Decision', description: 'متى تستحق التكلفة؟' },
      { title: 'Trade Secrets', description: 'NDAs، invention assignment، access control.' },
      { title: 'Enforcement Plan', description: 'Monitoring، cease & desist، litigation.' },
    ],
    outcomes: ['IP register', 'Filing schedule', 'Templates للـ NDAs', 'Enforcement protocol'],
    relatedKeywords: ['IP', 'ملكية فكرية', 'trademark', 'patent'],
    estimatedTimeMinutes: 120,
    difficulty: 'advanced',
  },
  {
    slug: 'build-customer-success',
    titleAr: 'بناء فريق Customer Success يقلل churn',
    titleEn: 'Build a Customer Success Team',
    metaDescriptionAr: 'CS الحديث = إيراد، مش cost center. كلميرون يبنيلك CS function يضاعف NRR.',
    metaDescriptionEn: 'Modern CS = revenue, not cost center. Build a CS function that doubles NRR.',
    heroIntroAr: '120% NRR يعني الشركة تنمو حتى بدون عملاء جدد. CS الصح يحقق هذا.',
    primaryAgents: ['marketing_orchestrator', 'plan_builder', 'hr_orchestrator'],
    steps: [
      { title: 'CS Maturity Model', description: 'Reactive → proactive → predictive.' },
      { title: 'Health Scoring', description: 'Composite metrics، early warnings.' },
      { title: 'Playbooks للـ lifecycle', description: 'Onboarding، adoption، expansion، renewal.' },
      { title: 'QBRs و EBRs', description: 'تحويل CS من tactical لـ strategic.' },
      { title: 'Expansion Motion', description: 'Upsell، cross-sell، advocacy.' },
    ],
    outcomes: ['CS playbook', 'Health score model', 'QBR template', 'NRR > 110%'],
    relatedKeywords: ['customer success', 'CS', 'NRR', 'expansion'],
    estimatedTimeMinutes: 120,
    difficulty: 'intermediate',
  },
  {
    slug: 'product-led-growth',
    titleAr: 'تطبيق Product-Led Growth في منتجك',
    titleEn: 'Apply Product-Led Growth',
    metaDescriptionAr: 'PLG: كيف تجعل منتجك يبيع نفسه. Aha moment، activation، viral loops، expansion.',
    metaDescriptionEn: 'PLG: make your product sell itself. Aha moment, activation, viral loops, expansion.',
    heroIntroAr: 'Slack، Notion، Figma كلها PLG. كلميرون يبنيلك PLG strategy لمنتجك.',
    primaryAgents: ['plan_builder', 'marketing_orchestrator', 'idea_validator'],
    steps: [
      { title: 'Time to Aha', description: 'تقليله من 30 دقيقة لـ 60 ثانية.' },
      { title: 'Activation Metrics', description: 'تحديد و قياس.' },
      { title: 'Viral Loops Design', description: 'K-factor > 1 = نمو exponential.' },
      { title: 'PQL Definition', description: 'Product Qualified Lead الصحيح.' },
      { title: 'Self-serve → Sales-assist', description: 'متى تتدخل sales.' },
    ],
    outcomes: ['PLG strategy', 'Activation funnel', 'Viral mechanics', 'PQL definition'],
    relatedKeywords: ['PLG', 'product-led', 'self-serve', 'viral'],
    industry: 'saas',
    estimatedTimeMinutes: 150,
    difficulty: 'advanced',
  },
  {
    slug: 'launch-podcast-business',
    titleAr: 'إطلاق بودكاست كأداة نمو',
    titleEn: 'Launch a Podcast as a Growth Tool',
    metaDescriptionAr: 'كيف تبني podcast يجلب لك عملاء، شركاء، واستثمارات في 90 يوم.',
    metaDescriptionEn: 'How to build a podcast that brings you customers, partners, and investments in 90 days.',
    heroIntroAr: 'Podcast = أعلى trust signal، أقل تكلفة. كلميرون يبنيلك podcast strategy احترافية.',
    primaryAgents: ['marketing_orchestrator', 'plan_builder'],
    steps: [
      { title: 'Niche & Format', description: 'Solo، interview، panel، أو narrative.' },
      { title: 'Tech Setup', description: 'Mic، software، hosting، editing.' },
      { title: 'Guest Pipeline', description: '20 guests للأشهر القادمة.' },
      { title: 'Distribution', description: 'YouTube، Spotify، newsletter snippets.' },
      { title: 'Monetization Strategy', description: 'Sponsors، lead gen، product sales.' },
    ],
    outcomes: ['Podcast launched', 'أول 10 episodes', '500+ subscribers', 'Pipeline من leads'],
    relatedKeywords: ['podcast', 'بودكاست', 'audio content', 'thought leadership'],
    estimatedTimeMinutes: 120,
    difficulty: 'intermediate',
  },
  {
    slug: 'startup-legal-foundations',
    titleAr: 'الأسس القانونية للستارت أب الجديد',
    titleEn: 'Legal Foundations for a New Startup',
    metaDescriptionAr: 'كل الـ legal docs اللي تحتاجها في أول سنة: incorporation، agreements، policies.',
    metaDescriptionEn: 'All legal docs you need in year one: incorporation, agreements, policies.',
    heroIntroAr: 'مشاكل قانونية بسيطة في البداية = كوارث في الـ Series A. كلميرون يبنيلك الأسس صح.',
    primaryAgents: ['legal_guide', 'cfo_agent', 'compliance'],
    steps: [
      { title: 'Incorporation', description: 'مصري vs Delaware vs Cayman.' },
      { title: 'Founder Agreement', description: 'Vesting، roles، dispute resolution.' },
      { title: 'IP Assignment', description: 'كل code/design ملك الشركة.' },
      { title: 'Employment Agreements', description: 'Templates، NDAs، non-compete.' },
      { title: 'Customer Contracts', description: 'ToS، privacy policy، MSA.' },
    ],
    outcomes: ['Incorporation completed', 'Cap table', 'Templates legal', 'Policies pages'],
    relatedKeywords: ['legal foundations', 'تأسيس قانوني', 'incorporation', 'founder agreement'],
    estimatedTimeMinutes: 180,
    difficulty: 'intermediate',
  },
  {
    slug: 'localize-product-arabic',
    titleAr: 'توطين منتجك عالمياً للسوق العربي',
    titleEn: 'Localize Your Global Product for Arabic Market',
    metaDescriptionAr: 'أكثر من ترجمة: التوطين الحقيقي يضاعف conversion في السوق العربي 3-5×.',
    metaDescriptionEn: 'More than translation: true localization triples conversion in Arabic markets.',
    heroIntroAr: 'i18n = trivial. l10n = صعب. كلميرون يفهم الفروقات الثقافية واللغوية.',
    primaryAgents: ['marketing_orchestrator', 'plan_builder'],
    steps: [
      { title: 'RTL Implementation', description: 'كل UI، كل components، كل edge cases.' },
      { title: 'Translation Quality', description: 'مش Google Translate. مترجمين خبراء.' },
      { title: 'Cultural Adaptation', description: 'Imagery، colors، examples، humor.' },
      { title: 'Local Payment & Support', description: 'Fawry، EGP، support بالعربية.' },
      { title: 'Local Marketing Channels', description: 'WhatsApp، Snapchat، influencers محليين.' },
    ],
    outcomes: ['Arabic version كامل', 'Cultural guide', 'Local payment integrated', 'Arabic support'],
    relatedKeywords: ['localization', 'توطين', 'Arabic UX', 'RTL'],
    estimatedTimeMinutes: 240,
    difficulty: 'advanced',
  },
  {
    slug: 'crisis-management',
    titleAr: 'إدارة الأزمات في الستارت أب',
    titleEn: 'Crisis Management for Startups',
    metaDescriptionAr: 'PR crisis، data breach، co-founder dispute، running out of cash. كلميرون يبنيلك خطة.',
    metaDescriptionEn: 'PR crisis, data breach, co-founder dispute, running out of cash. Build a plan.',
    heroIntroAr: 'كل startup ستواجه أزمة. الفرق بين النجاة والموت = جاهزية الخطة.',
    primaryAgents: ['legal_guide', 'compliance', 'plan_builder', 'marketing_orchestrator'],
    steps: [
      { title: 'Crisis Playbook', description: 'لكل سيناريو، خطة 24 ساعة.' },
      { title: 'Communication Templates', description: 'Internal، external، media، investors.' },
      { title: 'Legal Preparedness', description: 'Lawyer on call، insurance، compliance.' },
      { title: 'Tabletop Exercises', description: 'تدريب الفريق ربع سنوي.' },
      { title: 'Post-mortem Culture', description: 'Blameless، action items، learnings.' },
    ],
    outcomes: ['Crisis playbook', 'Templates', 'Insurance review', 'Quarterly drills'],
    relatedKeywords: ['crisis management', 'إدارة أزمات', 'PR crisis', 'incident response'],
    estimatedTimeMinutes: 120,
    difficulty: 'advanced',
  },
  {
    slug: 'build-board-of-advisors',
    titleAr: 'بناء Board of Advisors قوي',
    titleEn: 'Build a Strong Board of Advisors',
    metaDescriptionAr: 'كيف تختار، تجتذب، وتستفيد من Advisors. + templates للـ equity والاتفاقيات.',
    metaDescriptionEn: 'How to choose, attract, and leverage Advisors. + equity and agreement templates.',
    heroIntroAr: 'Advisors الصح = سنوات من التعلم في شهور. كلميرون يساعدك تبني board استراتيجي.',
    primaryAgents: ['plan_builder', 'legal_guide', 'opportunity_radar'],
    steps: [
      { title: 'تحديد الفجوات', description: 'أين تحتاج خبرة - tech، sales، industry، fundraising.' },
      { title: 'Target List', description: '10-15 advisor مثالي.' },
      { title: 'Outreach الذكي', description: 'Warm intros > cold emails.' },
      { title: 'Equity Compensation', description: '0.1-0.5% vesting لكل advisor.' },
      { title: 'Activation وقياس الـ ROI', description: 'Monthly check-ins، asks محددة.' },
    ],
    outcomes: ['Advisor list', '3-5 موقّعين', 'Advisor agreements', 'Cadence calls'],
    relatedKeywords: ['board of advisors', 'مستشارون', 'mentors', 'startup advisors'],
    estimatedTimeMinutes: 90,
    difficulty: 'intermediate',
  },
  {
    slug: 'master-unit-economics',
    titleAr: 'إتقان Unit Economics لمنتجك',
    titleEn: 'Master Your Product Unit Economics',
    metaDescriptionAr: 'CAC، LTV، Payback، Magic Number: الأرقام التي يفحصها كل VC.',
    metaDescriptionEn: 'CAC, LTV, Payback, Magic Number: numbers every VC checks.',
    heroIntroAr: 'Unit economics سيئة = موت محقق. كلميرون يحسب لك كل metric ويقترح تحسينات.',
    primaryAgents: ['cfo_agent', 'plan_builder'],
    steps: [
      { title: 'احسب CAC الحقيقي', description: 'Blended + paid + organic.' },
      { title: 'احسب LTV الواقعي', description: 'Cohort-based، not aggregate.' },
      { title: 'LTV:CAC Target', description: '3:1 ممتاز، 5:1 استثنائي.' },
      { title: 'CAC Payback', description: '< 12 شهر = صحي.' },
      { title: 'Sensitivity Analysis', description: 'ماذا لو ارتفع churn 5%؟ خفضت CAC 20%؟' },
    ],
    outcomes: ['Unit economics model', 'Cohort analysis', 'Recommendations لتحسين'],
    relatedKeywords: ['unit economics', 'CAC', 'LTV', 'metrics'],
    estimatedTimeMinutes: 90,
    difficulty: 'advanced',
  },
  {
    slug: 'build-engineering-team',
    titleAr: 'بناء فريق هندسي عالمي المستوى',
    titleEn: 'Build a World-Class Engineering Team',
    metaDescriptionAr: 'من أول CTO إلى team of 50: hiring، processes، culture، compensation.',
    metaDescriptionEn: 'From first CTO to team of 50: hiring, processes, culture, compensation.',
    heroIntroAr: 'فريق هندسي ممتاز = velocity ممتازة. كلميرون يبنيلك engineering org.',
    primaryAgents: ['hr_orchestrator', 'cfo_agent', 'plan_builder'],
    steps: [
      { title: 'CTO vs VP Eng vs first hire', description: 'متى تحتاج أيهم.' },
      { title: 'Hiring Funnel', description: 'Sourcing، screening، interview loop.' },
      { title: 'Engineering Levels', description: 'L3-L7، promotion criteria.' },
      { title: 'Engineering Culture', description: 'Code review، on-call، blameless postmortems.' },
      { title: 'Tools & Infrastructure', description: 'CI/CD، observability، dev productivity.' },
    ],
    outcomes: ['Eng org plan', 'Leveling guide', 'Hiring scorecards', 'Culture doc'],
    relatedKeywords: ['engineering team', 'فريق هندسي', 'CTO', 'eng culture'],
    estimatedTimeMinutes: 180,
    difficulty: 'advanced',
  },
  {
    slug: 'product-discovery-process',
    titleAr: 'عملية Product Discovery احترافية',
    titleEn: 'Professional Product Discovery Process',
    metaDescriptionAr: 'منهجية Marty Cagan للـ discovery: تجنب بناء features غير مرغوبة.',
    metaDescriptionEn: 'Marty Cagan discovery methodology: avoid building unwanted features.',
    heroIntroAr: 'Build the right thing > build it right. كلميرون يبنيلك discovery process.',
    primaryAgents: ['idea_validator', 'plan_builder', 'marketing_orchestrator'],
    steps: [
      { title: 'Continuous Discovery Habits', description: 'Weekly customer interviews.' },
      { title: 'Opportunity Solution Tree', description: 'Outcomes → opportunities → solutions.' },
      { title: 'Assumption Mapping', description: 'فصل value، usability، feasibility، viability.' },
      { title: 'Prototype Testing', description: 'Figma → 5-user tests → iterate.' },
      { title: 'Decision Criteria', description: 'Build، pivot، أو kill بسرعة.' },
    ],
    outcomes: ['Discovery cadence', 'Templates للـ interviews', 'Decision framework'],
    relatedKeywords: ['product discovery', 'product management', 'discovery'],
    industry: 'saas',
    estimatedTimeMinutes: 150,
    difficulty: 'advanced',
  },
  {
    slug: 'build-community',
    titleAr: 'بناء مجتمع حول منتجك',
    titleEn: 'Build a Community Around Your Product',
    metaDescriptionAr: 'Community = أقوى moat. كلميرون يبنيلك community من 0 لـ 10K عضو نشط.',
    metaDescriptionEn: 'Community = strongest moat. Build from 0 to 10K active members.',
    heroIntroAr: 'Stripe، Notion، Figma كلها بنوا communities ضخمة. كلميرون يساعدك تفعل نفس الشيء.',
    primaryAgents: ['marketing_orchestrator', 'plan_builder'],
    steps: [
      { title: 'اختر المنصة', description: 'Discord، Slack، Circle، أو Discourse.' },
      { title: 'Founding Members', description: 'أول 100 عضو يصنعون الثقافة.' },
      { title: 'Content & Rituals', description: 'AMAs، events، challenges، threads.' },
      { title: 'Moderation وSafety', description: 'Guidelines، moderators، escalation.' },
      { title: 'Community-led Growth', description: 'Member referrals، UGC، advocacy.' },
    ],
    outcomes: ['Community launched', 'أول 1000 عضو', 'Engagement metrics', 'Community playbook'],
    relatedKeywords: ['community building', 'مجتمع', 'community-led', 'Discord'],
    estimatedTimeMinutes: 120,
    difficulty: 'intermediate',
  },
];

export function getUseCaseBySlug(slug: string): UseCase | undefined {
  return USE_CASES.find((uc) => uc.slug === slug);
}

export function getAllUseCaseSlugs(): string[] {
  return USE_CASES.map((uc) => uc.slug);
}

export function getUseCasesByIndustry(industry: string): UseCase[] {
  return USE_CASES.filter((uc) => uc.industry === industry);
}
