/**
 * AUTO-GENERATED by scripts/generate-api-clients.mjs — do not edit by hand.
 * Source: docs/api/services/pdf-worker.openapi.json
 *
 * Service: pdf-worker
 */
 

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract */
        post: operations["extract_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_extract_extract_post */
        Body_extract_extract_post: {
            /**
             * File
             * @description PDF document to extract
             */
            file: string;
        };
        /** ChunkOut */
        ChunkOut: {
            /** Text */
            text: string;
            /** Charcount */
            charCount: number;
            /** Pagehint */
            pageHint?: number | null;
        };
        /** ExtractOut */
        ExtractOut: {
            /** Text */
            text: string;
            /** Pagecount */
            pageCount: number;
            /** Language */
            language: string;
            /** Charcount */
            charCount: number;
            /** Chunkcount */
            chunkCount: number;
            /** Chunks */
            chunks: components["schemas"]["ChunkOut"][];
            /** Extractionpath */
            extractionPath: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    extract_extract_post: {
        parameters: {
            query?: {
                target_chars?: number;
                max_chars?: number;
                overlap?: number;
                aggressive_normalize?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
