// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kalmeron-hero/MinimalPremium.tsx": () => import("../components/mockups/kalmeron-hero/MinimalPremium.tsx"),
  "./components/mockups/kalmeron-hero/OperatingSystem.tsx": () => import("../components/mockups/kalmeron-hero/OperatingSystem.tsx"),
  "./components/mockups/kalmeron-hero/Storytelling.tsx": () => import("../components/mockups/kalmeron-hero/Storytelling.tsx")
};
