// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand/BrandSystem.tsx": () => import("../components/mockups/brand/BrandSystem.tsx"),
  "./components/mockups/brand/ColorTokens.tsx": () => import("../components/mockups/brand/ColorTokens.tsx"),
  "./components/mockups/brand/HeroRefined.tsx": () => import("../components/mockups/brand/HeroRefined.tsx"),
  "./components/mockups/brand/LogoShowcase.tsx": () => import("../components/mockups/brand/LogoShowcase.tsx"),
  "./components/mockups/brand/TypeSystem.tsx": () => import("../components/mockups/brand/TypeSystem.tsx"),
  "./components/mockups/kalmeron-hero/MinimalPremium.tsx": () => import("../components/mockups/kalmeron-hero/MinimalPremium.tsx"),
  "./components/mockups/kalmeron-hero/OperatingSystem.tsx": () => import("../components/mockups/kalmeron-hero/OperatingSystem.tsx"),
  "./components/mockups/kalmeron-hero/Storytelling.tsx": () => import("../components/mockups/kalmeron-hero/Storytelling.tsx")
};
